### ISSUE TITLE
Game crashes when trying to start WWE inside FTB ultimate reloaded

### ISSUE THREAD

**Issue by rmit-s3440880-LaiLim-Chan** [THEREALWWEFAN231/wwe#1]
[error.log](https://github.com/THEREALWWEFAN231/wwe/files/3048632/error.log)
Please see attached log, I'm running on MultiMC 5 with the FTB ultimate reloaded 1.5.0 for minecraft 1.12.2

**Comment by THEREALWWEFAN231** [comment]
Thats "pretty interesting", Theres some conflict with GuiMainMenu but the weird thing is it shouldent be conflicting unless one of them mods have the same priority as wwe, which i set to 9999, actually now that i think of it they most likely "overrided" the main menu and now wwe is trying to inject and failing, this isent a wwe issue, you might be able to "fix it" by opening the wwe jar with winwar or something, editing mixins.wwefan.json and removing the line, "MixinGuiMainMenu", then trying to load, wwe wont edit the main menu so if you wanted to do something there you cant, and tbh it might fail on another mixin.
