### ISSUE TITLE
Optimise WWE Performance

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/wwe#10]
**WWE version:** 
2.7 -> 2.7.2
**Minecraft version:** 
1.12.2 (probably every)
**Operating system:** 
Win10 Home
**Optifine/Other mods:** 
WorldEdit,
Schematica,
Optifine,
LunatriusCore,
EtikaHack (private client),
EMC,
ClientCommands
**Whats the issue:** 
sometimes fps decreases (under 60) even though im using a GTX 1060
**Crash-report(Would be very useful also please format):**

**Comment by Vonr** [comment]
GTX 1060 isn't going to guarantee 60 fps. Especially above 1.8.9

**Comment by IAmWolfie** [comment]
WWE doesn't effect my FPS majorly unless I'm using Search or something.

**Comment by mememasterlord32345** [comment]
It might be an issue with the other mods you have installed personally I don't have fps issues.

**Comment by Discusser** [comment]
> GTX 1060 isn't going to guarantee 60 fps. Especially above 1.8.9

Hold up, you're telling me an _Acer Predator Helios 300_ can run Metro Exodus, Just Cause 4, Doom (the new one), Battlefield V, etc.. but not minecraft?

**Comment by VKartze** [comment]
> Hold up, you're telling me an _Acer Predator Helios 300_ can run Metro Exodus, Just Cause 4, Doom (the new one), Battlefield V, etc.. but not minecraft?

yes, cuz mc is a single-thread application

**Comment by Paralusion** [comment]
Minecraft, suprisingly needs a good CPU and graphics card to run well from. 
Try deleting your other mods and turning off a few of your render modules. This could also be a problem with your OptiFine settings.

**Comment by Zernaie** [comment]
turn mc settings down??? Im running a gtx 1050 and I can play it fine even using 128x packs like PureBDcraft with most settings up. Try getting some fps mods like foamfix

**Comment by Paralusion** [comment]
no reply has been given in 14 days, this can be closed

**Comment by THEREALWWEFAN231** [comment]
I dont have this problem and as others said they dont have it so it must be one of your mods
