### ISSUE TITLE
[Suggestion] Scripting system

### ISSUE THREAD

**Issue by Vonr** [THEREALWWEFAN231/wwe#104]
**Minecraft Version**
yes

**What is the suggestion**
Make a scripting system based on Javascript or some other easy-to-understand language.

**Why it will be useful**
Allows users to make their own scripts that can be shared and potentially make new bypasses with the help of the community.

**Comment by Vonr** [comment]
example of a successful scripting system is LiquidBounce btw

**Comment by Paralusion** [comment]
Already possible because the smart decision of making it a Forge/Fabric mod was made. You can already code your own additions using Java.

**Comment by THEREALWWEFAN231** [comment]
Sorry but this isent happening any time soon...
