### ISSUE TITLE
Suggestion: Profiles

### ISSUE THREAD

**Issue by MrN00BZ** [THEREALWWEFAN231/wwe#105]
**Minecraft Version**
1.14.3

**What is the suggestion**
Profiles  

**Why it will be useful**
So you have a profile for every world/server that you play on. Example: you play on some no rules anarchy server and on a singleplayer world so the waypoints don't mix.

**Comment by SylveonBottle** [comment]
Profiles are already in the client, no? 
![image](https://user-images.githubusercontent.com/17802843/61391573-99240400-a882-11e9-9ff8-279a0de5abc2.png)
