### ISSUE TITLE
Light ESP

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#113]
**Quick Description**
An ESP / rectangle that would display on the ground of where mobs can spawn during the day/night, in yellow/red.

**The Issue**
You're unable to see where mobs can spawn without turning off fullbright and making it harder to see. Using this, you'd be able to see exact spawns and place torches/blocks accordingly.
You'd also be able to use this to make mob farms more efficient.

**Comment by Paralusion** [comment]
not a feature for a hacked client, so no

**Comment by THEREALWWEFAN231** [comment]
This was added in 3.0
