### ISSUE TITLE
Base Finder

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#115]
**Quick Description**
A method for finding bases in scenarios where you may accidentally skip over them, by highlighting blocks only players can place.

**The Issue**
Currently your only means of finding bases is either with xray or just by stumbling around them. When you're flying at high speeds, it's incredibly easy to miss a farm deep underground or a building high in the air.
Base Finder would show an ESP around these blocks that can't be found naturally (planks, doors, glass, etc), as well as cobblestone (incase of hidden mines).

**My Suggestion for Developers**
Show a visual ESP around blocks that do not spawn naturally. Maybe tracers to help with stuff too high/low.

**Comment by Paralusion** [comment]
already a thing, it's called Search. a preset for non-natural blocks could be a thing though
