### ISSUE TITLE
XrayBug

### ISSUE THREAD

**Issue by matthewsf619** [THEREALWWEFAN231/wwe#117]
2.7.2
1.14.3 
64 bit
Every time I load in xray and then type in the chat /.xray add diamond_ore
nothing happens it just pops up unknown command /.xray add diamond_ore click here. and when I click still nothing happens. help.

**Comment by THEREALWWEFAN231** [comment]
the command is .xray add diamond_ore, no slash, just type in chat, .xray add diamond_ore, feel free to reopen this.
