### ISSUE TITLE
AutoPrefix/AutoSuffix/AutoText

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/wwe#12]
**Minecraft Version**
every
**What is the suggestion**
Allows you to add text to your message (in chat) at the beginning or at the end.
if i say 

> .autoText ☭

and then i type 

> WWE on top

 in chat, it will display the following:

> ☭ WWE on top ☭

and maybe add options to customize
e.g: one symbol at the beginning and another on at the end:

> ☭ communistHitler 卐

and the command for that would be 

> .autoText ☭ / 卐

and u can also insert multiple characters
e.g: 

> ☭ 卐 2b2thack ☭ 卐

 and the command for that is 

> .autoText ☭ 卐 / ☭ 卐

**Why it will be useful**
Doesn't really have a use, basically a fun hack.

**Comment by THEREALWWEFAN231** [comment]
If i added that, that means wwe is stooping too low
