### ISSUE TITLE
Entity Fly

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#121]
**What is the suggestion**
Not sure how but apparently you can make entities like horse fly. Done using `.vanish dismount` while on a horse, then just flying up. Killed the horse though.
**Why it will be useful**
Would be better for quickly flying your horse or whatever up a steep hill or another without having to invoke the vanish commands

**Comment by Paralusion** [comment]
boatfly

**Comment by THEREALWWEFAN231** [comment]
^
