### ISSUE TITLE
.say

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#123]
"Say .help or you'll be banned"
I got banned.

**Comment by SylveonBottle** [comment]
Legit the stupidest thing I've ever been banned for, can't believe I have to do these stupid "hacker test" in 2019.

Even more stupid that I actually couldn't do it.

**Comment by Paralusion** [comment]
yes

**Comment by THEREALWWEFAN231** [comment]
This was done in 3.0 you could have used .prefix :eyes:
