### ISSUE TITLE
NoFall activates when <3 blocks

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#135]
NoFall seems to be activating, even when you're just sprint-jumping. This seems to be causing a small issue with certain anticheat servers, where instead of flagging the user once when avoiding damage, it appears to be constantly flagging them.

**Comment by THEREALWWEFAN231** [comment]
This is to make it work 100% on vanilla servers

**Comment by THEREALWWEFAN231** [comment]
As said above^, this isent going to happen because all of the aristois kids crying about no fall not working on wwe client
