### ISSUE TITLE
.friends list

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/wwe#14]
**Minecraft Version**
every
**What is the suggestion**
Allows you to view your friend list.
**Why it will be useful**
Useful if you want to clean it of inactive players

**Comment by Paralusion** [comment]
A friend manager could be added instead, look at KiLo friend manager or any GUI friend managers. 
This could give stuff like actual chats, maybe even groupchats through friends themselves ingame.

**Comment by THEREALWWEFAN231** [comment]
This was added in 3.0
