### ISSUE TITLE
Make Aim Assist look smoother

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#142]
**What is the suggestion**
Make Aim Assist look smoother. it's literally just aimbot right now. Just look at half (half of a half, rather) the distance tick or so.
**Why it will be useful**
probably wouldn't get instantly banned

**Comment by Paralusion** [comment]
wwe is still not a ghost client..

**Comment by THEREALWWEFAN231** [comment]
This was kind of done in 3.0, i think its going be the best im going add to wwe client
