### ISSUE TITLE
"OpenGL Error: 1283 (Stacked Overflow)"

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/wwe#16]
**WWE version:** 
2.7.2
**Minecraft version:** 
1.12.2
**Operating system:** 
Win10 home
**Optifine/Other mods:** 
![image](https://user-images.githubusercontent.com/47938380/59793447-438a2500-92df-11e9-9ad2-a8c3a6006970.png)
**Whats the issue:** 
Sometimes while playing, the game randomly gives me this error and ChestESP or water starts freaking out and going in the air.
**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Do you have way points on?

**Comment by Discusser** [comment]
Don't think so

**Comment by Nhjb1** [comment]
wtf is etika hack

**Comment by Discusser** [comment]
> wtf is etika hack

A private client

**Comment by dan28dan** [comment]
the same problem when I open freecam

**Comment by THEREALWWEFAN231** [comment]
Im going say this isent wwe considering you have 8 mods and dont have way points on
