### ISSUE TITLE
Set a limit to the .value command

### ISSUE THREAD

**Issue by Discusser** [THEREALWWEFAN231/wwe#17]
**Minecraft Version**
every
**What is the suggestion**
Don't allow the player to put the .value over the 32bit limit, (once put entityspeed speed at 64bit limit on 2b2t and crashed my game)
**Why it will be useful**
So that games dont crash

**Comment by mememasterlord32345** [comment]
At that point you are basically trying to crash your game.

**Comment by THEREALWWEFAN231** [comment]
> At that point you are basically trying to crash your game.

Yeah lmao, but we will add a limit

**Comment by THEREALWWEFAN231** [comment]
actually, we wont...
