### ISSUE TITLE
NoFall: "Waterbucket"

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#175]
**Minecraft Version**

**What is the suggestion**
Move WaterBucket as a mode for Nofall
**Why it will be useful**
Cleans clutter, it's technically a form of not taking fall damage

**Comment by DrakCZ** [comment]
hey i am not mod but waterbucket is broken dont work most times cos server lag + when u fall in between 2 blocks its will kill you

**Comment by THEREALWWEFAN231** [comment]
This was done in 3.0
