### ISSUE TITLE
Make Water Bucket better

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#176]
Make look packet/server-side, as well as placing water onto the block unerneath the player (check the first block directly below the player, check if there's an adjacent block to put the water on first (you can put the water on the side of blocks and land in it faster than directly ontop of the block you'll land on, this saves both time and lives)

Also make it pick up the water

**Comment by THEREALWWEFAN231** [comment]
Its actually kind of hard to make the water place server side... the bucket placements are server side, its hard to explain il ltry some other time

**Comment by THEREALWWEFAN231** [comment]
No fall water bucket mode in 3.0 10/10 best water bucket ull ever find

**Comment by RealIndrit** [comment]
100% skidded from Baritone MLG Waterbucket fall lol

**Comment by THEREALWWEFAN231** [comment]
... I didn't even look at baritones water bucket, and I'm almost certain baritone cant beat him, so id suggest rethinking.
