### ISSUE TITLE
Anti Levitate: "Motion" results in constantly flying. 

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#178]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.3
**Operating system:** W10
**Optifine/Other mods:** None
**Whats the issue:**
 When enabled, you just sorta fly straight

**Comment by THEREALWWEFAN231** [comment]
Thats kind of what this mode does, use remove or what ever its called if you dont like it, altough i suggest aura
