### ISSUE TITLE
Waypoint Suggestion

### ISSUE THREAD

**Issue by mememasterlord32345** [THEREALWWEFAN231/wwe#19]
**Minecraft Version: All**

**What is the suggestion**
Make waypoints more like Future
http://media.methamphetamine.solutions/of45ias3.png

**Why it will be useful**
Using waypoints with the current beacon thing over long distances is basically impossible.

**Comment by THEREALWWEFAN231** [comment]
There is a tracer "option", .waypoints edit name, then click beacon till you see tracer

**Comment by mememasterlord32345** [comment]
Alright thank you but the tracers specifically with the waypoints seem to be quite bugged.
Heres a vid http://media.methamphetamine.solutions/dji4k6o5.mp4

**Comment by THEREALWWEFAN231** [comment]
Tracer is fixed in the next version, although all tracers dont work in third person.
