### ISSUE TITLE
ItemESP: "Shaders"

### ISSUE THREAD

**Issue by SylveonBottle** [THEREALWWEFAN231/wwe#196]
**Minecraft Version**

**What is the suggestion**
Option to use shaders on items instead of a box
**Why it will be useful**
instead of just a plain box, a shader around the items would make it easier to distinguish through walls.

**Comment by THEREALWWEFAN231** [comment]
Well there is a outline mode in 3.0, but its not nice with items, in 3.1 which will be available to donators(< 1 week) before free release theres a shader option added which is what you want
