### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Semichaotic** [THEREALWWEFAN231/wwe#2]
**WWE version:2.5** 
**Minecraft version:1.13.2** 
**Operating system: Win 10 Pro** 
**Optifine/Other mods: no other mods. standalone client** 

**Whats the issue: Chest ESP outline mode on minecarts shows as box mode**

**Comment by THEREALWWEFAN231** [comment]
Well its not a bug, i did that on purpose, i honestly dident even think i could outline a minecart i havent tried, ill try it.

**Comment by Semichaotic** [comment]
oh, felt just kinda off
