### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Burgerzzzz** [THEREALWWEFAN231/wwe#207]
**Minecraft Version**
1.12.2
**What is the suggestion**
Make entity speed higher than 5.
**Why it will be useful**
It will be useful because you can travel a lot faster on an animal so you can get to places faster. Since the animal is fast not the player, anti-cheat won't detect it as much.

**Comment by BleachDrinker420** [comment]
use ".value entity_speed speed [amount]" to set the speed higher
