### ISSUE TITLE
OptiFine 1.14.3 HD U F2 Xray Bug

### ISSUE THREAD

**Issue by Tracder98** [THEREALWWEFAN231/wwe#208]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.3
**Operating system:** Win10
**Optifine/Other mods:** OptiFine 1.14.3 HD U F2

**Whats the issue:** 
XRay doesn't seems to work correctly with the new OptiFine version. If i press X in version F2 no blocks dissapear. Adding blocks or removing them doesnt change that. Everthing stays solid.
**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Do you have the fabric api mod, try removing that and any mods that use that, please reply

**Comment by purush97** [comment]
I had the same issue, I was running OptiFabric, Optifine, Fabric API, and VoxelMap mod along with WWE. Was able to use xray again after removing all of those four.
