### ISSUE TITLE
Xray Bug 1.14.4

### ISSUE THREAD

**Issue by galihcanfly** [THEREALWWEFAN231/wwe#210]
**WWE version: 2.7.2** 
**Minecraft version: 1.14.4** 
**Operating system: Win 10** 
**Optifine/Other mods: OptiFine 1.14.4 HD U F2 pre1 ** 

**Whats the issue:** 
Xray is not working with optifine 1.14.4 HD U F2 pre1. All blocks don't disappear and actually activate full bright instead. (*update : even without optifine, xray still doesn't work )

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Remove optifine & optifabric to fix it, i havent looked into it yet but i will soon, i know whats going on but dont know how to fix it(you may also have to remove fabric api if you have that)

**Comment by galihcanfly** [comment]
Oh yeah , it worked , thankss
