### ISSUE TITLE
Thirdperson, Barrel, Furnace & items glitch, EDIT way points

### ISSUE THREAD

**Issue by ForGamezCZ** [THEREALWWEFAN231/wwe#211]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.4
**Operating system:** Windows 10
**Optifine/Other mods:** None

**Whats the issue:** After loading up my Minecraft, I noticed that I couldn't use thirdperson, going to TP caused blackscreen, no possible solution worked but then I went to Nether and back to normal world, that for some reason fixed it. 
Preview: https://i.imgur.com/Ziv4lyt.png

Another visual glitch I found is that all the barrels, furnaces and dropped items were all gray. Chests were okay tho.
Preview: https://i.imgur.com/kpcnD1R.png

**Crash-report(Would be very useful also please format):** None

**Comment by THEREALWWEFAN231** [comment]
This would be way points reeeeeeeeeeeeeeeeeeee, i dont know how to replicate, its great though that you left pictures. ill look later

**Comment by THEREALWWEFAN231** [comment]
Im going close this as i know its an issue and will be fixed some time in the future, altough i will add a message when way points is enabled saying it causes glitches
