### ISSUE TITLE
Elytras break with NoFall

### ISSUE THREAD

**Issue by AJJIV** [THEREALWWEFAN231/wwe#213]
**2.7.2:** 
**1.14.4:** 
**Mac OSX:** 
**Optifine_1.14.4_HD_U_F2_pre1/OptiFabric:** 

**Elytras break entirely when NoFall is turned on:**

**Comment by THEREALWWEFAN231** [comment]
I really have no idea how to fix this, i tried but couldent, i added a warning message.
