### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DrakCZ** [THEREALWWEFAN231/wwe#214]
**WWE version:2.7.2
**Minecraft version:1.14.4
**Operating system:W10
**Optifine/Other mods:no

**Whats the issue: Autosign - text just will get deleted when i place the sign it will be there for 2 ticks i guess i am playing on spigot newest version

**Crash-report(Would be very useful also please format):i dont get crash report

**Comment by DrakCZ** [comment]
when text is too long u cant paste it by default but u have to pres fullscreen button

**Comment by Paralusion** [comment]
This is also the same on vanilla servers, pressing F11 or whatever your system full screen key is places the text. Works fine on 1.12.2, just never on any 1.14 versions.

**Comment by THEREALWWEFAN231** [comment]
Welllll its "fixed" for the next update, there's no easy way to do it in 1.13+ although immediately having the mod close the sign would also work that will be added in a future version
