### ISSUE TITLE
Item Durability Display

### ISSUE THREAD

**Issue by AJJIV** [THEREALWWEFAN231/wwe#216]
**Minecraft Version**
1.14.4
**What is the suggestion**
Show durability when hovering over items that can be damaged. Ex: 57/256
**Why it will be useful**
This would make it more useful to see exactly how much more your gear and items can take and would be a useful utility to have.

**Comment by BleachDrinker420** [comment]
bruh, f3+h

**Comment by THEREALWWEFAN231** [comment]
What bleach said....
