### ISSUE TITLE
Optifine 1.14 / Shader Pack White Screen Bug.

### ISSUE THREAD

**Issue by vungsung** [THEREALWWEFAN231/wwe#217]
<h2>IKR Optifine is conflicting with WWE X-ray, just to note there's one more bug with specific shader packs.</h2>

Bug screenshot: ![](https://i.imgur.com/xg31XMt.png)

Normal screenshot: ![](https://i.imgur.com/b4icJse.png)

Environment: [**Fabric Loader 0.4.8 Build 157 1.14.4**](https://fabricmc.net/) / [**WWE 2.7.2**](https://wweclient.com/Download.php) / [**Optifine (Preview) 1.14.4**](https://optifine.net/downloads) / [**Optifabric 0.4.3**](https://github.com/modmuss50/OptiFabric/releases)
Conflicted Shaders: [**projectLUMA - v1.00**](https://dedelner.net/projectluma/) / [**KUDA-Shaders v6.1 Legacy**](https://dedelner.net/kuda-shaders/)

<h3>
Some notes: 

1. After I removed WWE, the shader packs worked well. And then I put WWE jar back to the mods folder, the bug is back, which means WWE is one of the keys.

2. Kuda-Based shader packs are confirmed impacted by the bug.

3. When pressing ESC (entering the pause menu), game seems to be re-rendering (refreshing) the whole screen "once", and then when exiting the pause menu, game seems to be re-rendering (refreshing) once again.

4. Every time you exit the pause menu, you get switched between bugged or normal status. E.g. Screen displays well, after pause and re-continue the game, the screen becomes white (bugged), vice versa.
</h3>

Thanks for understanding, any advices are welcome.

**Comment by Paralusion** [comment]
Thanks for the report, OptiFine 1.14.4 is still very new and is in preview version, I'm not sure when THEREALWWEFAN321 will work on making it work completely, but it's probably not top-priority.

**Comment by vungsung** [comment]
Thanks for replying. I've tried Optifine 1.14.3 stable release, same problem, so maybe this bug is not that simple.

**Comment by THEREALWWEFAN231** [comment]
Not really something i can/care to change
