### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by usma2019** [THEREALWWEFAN231/wwe#218]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.4
**Operating system:**widows 
**Optifine/Other mods:** 

**Whats the issue:** xray dont work. You cant see ores. thank you. ;)

**Crash-report(Would be very useful also please format):**

**Comment by Paralusion** [comment]
Try removing Fabric API in your mods folder, or OptiFabric and OptiFine.

**Comment by THEREALWWEFAN231** [comment]
No "easy way we can fix it" what para said it correct
