### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by codemaster101gangster** [THEREALWWEFAN231/wwe#219]
**WWE version:** 1.14.4
**Minecraft version:** 1.14.3
**Operating system:** Windows 10 Home
**Optifine/Other mods:** none

**Whats the issue:** 
When trying to trade with a villager it kicks you out of the game. 
![Canttradewithvillager](https://user-images.githubusercontent.com/20823229/61821138-2f749e80-ae1c-11e9-8b5f-0540b731ce78.jpg))

**Crash-report(Would be very useful also please format):**

**Comment by Paralusion** [comment]
This was already known, but thanks for the report.

**Comment by THEREALWWEFAN231** [comment]
Fixed in next update
