### ISSUE TITLE
Suggestion Log Out Spots both

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#228]
**Minecraft Version**
All
**What is the suggestion**
Have an option "both" for Log Out Spot, to have both ESP and TAB.
**Why it will be useful**
idk i find it cooler

**Comment by THEREALWWEFAN231** [comment]
ESP and TAB? tab meaning the mode?... that wouldent make sense?

**Comment by Paralusion** [comment]
You have two modes, ESP and Tab,

**Comment by Paralusion** [comment]
I would want to have both modes enabled at once.

**Comment by THEREALWWEFAN231** [comment]
Im not understanding.. theres two modes, Tab and Cache and a option for esp, the mode is the way of detecting when a player left/joined, so i dont know why you would need Tab and Esp on?

**Comment by Paralusion** [comment]
once again, my intelligence seems to have lowered since a few days ago
