### ISSUE TITLE
Suggestion baritone

### ISSUE THREAD

**Issue by PostmanTap** [THEREALWWEFAN231/wwe#230]
**Minecraft Version**
1.14.4
**What is the suggestion**
baritone compatible again please :)

**Comment by BleachDrinker420** [comment]
baritone 1.14 doesn't have a api yet, you can't use add something that doesn't exist

**Comment by PostmanTap** [comment]
> baritone 1.14 doesn't have an api yet, you can't just add something that doesn't exist

ammmm wym
http://prntscr.com/ok1h8t
https://github.com/cabaletta/baritone/releases/tag/v1.3.4

**Comment by THEREALWWEFAN231** [comment]
I am/was already working on it for fabric....
