### ISSUE TITLE
MixinTargetAlreadyLoadedException Critical problem

### ISSUE THREAD

**Issue by BugFinder78** [THEREALWWEFAN231/wwe#235]
**WWE version: 2.7.2** 
**Minecraft version: 1.12.2** 
**Operating system: WIN10** 
**Optifine/Other mods: Tekxit 3 ** 

**Whats the issue:** 
The game immediately crashes following launch and this seems to happens in other mod packs in the Technic launcher.
**Crash-report(Would be very useful also please format):**
[techniclauncher.log](https://github.com/THEREALWWEFAN231/wwe/files/3439003/techniclauncher.log)

**Comment by THEREALWWEFAN231** [comment]
I have no idea why this is happening, by chance do you have two wwe jars, its legit adding it two times, which doesn't usually happen, so something else is messing it up, im going close this for now, feel free to reply/reopen it
