### ISSUE TITLE
Bug XCarry causes Inventory desync

### ISSUE THREAD

**Issue by blockparole** [THEREALWWEFAN231/wwe#238]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.4
**Operating system:** Windows 10
**Optifine/Other mods:**
MultiMC 5 0.6.6-1341
fabric-0.5.0.33
optifabric-0.4.3
OptiFine_1.14.4_HD_U_F2_MOD

**Whats the issue:**
Enabling XCarry causes Inventory desync.
Changes to Inventory via Player Menu are not synced correctly and get reset on Inventory Update.

**How to reproduce:**
Turn off all Modules but XCarry.
Move Items in Inventory.
Update Inventory.

Thinking about it, I had the same Problem in another Client. Does XCarry just cancel all Inventory Events? :open_mouth:

**Comment by BleachDrinker420** [comment]
Yes, xcarry just cancels all inventory close packets, not a bug
