### ISSUE TITLE
Bug Scaffold does not replace Grass

### ISSUE THREAD

**Issue by blockparole** [THEREALWWEFAN231/wwe#240]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.4
**Operating system:** Windows 10
**Optifine/Other mods:**
MultiMC 5 0.6.6-1341
fabric-0.5.0.33
optifabric-0.4.3
OptiFine_1.14.4_HD_U_F2_MOD

**Whats the issue:**
Scaffold does not replace Grass.

**Comment by THEREALWWEFAN231** [comment]
ahh yes i saw this too

**Comment by THEREALWWEFAN231** [comment]
Then was fixed in 3.0
