### ISSUE TITLE
Bug Outline ESP not respecting settings in Outline mode

### ISSUE THREAD

**Issue by blockparole** [THEREALWWEFAN231/wwe#242]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.4
**Operating system:** Windows 10
**Optifine/Other mods:**
MultiMC 5 0.6.6-1341
fabric-0.5.0.33
optifabric-0.4.3
OptiFine_1.14.4_HD_U_F2_MOD 

**Whats the issue:**
Outline ESP does not use supplied configuration switches in Outline mode.

**How to reproduce:**
Turn off all modules but Outline ESP.
Turn mode to Outline and turn off all targets.
Look at mobs or animals.

![Screenshot](https://i.imgur.com/ty6cvK7.png)

**Comment by THEREALWWEFAN231** [comment]
"Fixed"
