### ISSUE TITLE
Suggestion/bug recode waypoints

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#253]
**Minecraft Version**
All
**What is the suggestion**
Recode waypoints completely
**Why it will be useful**
It's hella buggy

**Comment by THEREALWWEFAN231** [comment]
ah okay so if you turn tracers on after you turn waypoints on this bug appears, just a note

**Comment by THEREALWWEFAN231** [comment]
This has been fixed(I think, I had it a couple times but could never replicate it but I think I fixed the issue) in the next pre-build(for donators) and publically released in 3.1.
