### ISSUE TITLE
Bug I was playing on a server I had blink on and got disconected and when I try to log back in I can't cuz blink is on and I have no way 2 turn it off so i'm basicly banned from wwe

### ISSUE THREAD

**Issue by NameChqnge** [THEREALWWEFAN231/wwe#258]
**WWE version:** 2.7.2
**Minecraft version:** 1.12.2
**Operating system:** umm iDK what this is
**Optifine/Other mods:**  no

**Whats the issue:** 

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Close minecraft, go to your .minecraft folder, wwe, Modules.txt, remove Blink, save and start minecraft, this is already fixed for when 2.8 releases
