### ISSUE TITLE
[Bug] Direct login not working

### ISSUE THREAD

**Issue by Rex109** [THEREALWWEFAN231/wwe#259]
**WWE version: 1.14.4** 
**Minecraft version: 1.14.4** 
**Operating system: Windows 10** 
**Optifine/Other mods: No** 

**Whats the issue: Direct login is not working for me, by clicking the login button either with fields empty or filled nothing is happening, nor changing my name** 

**Crash-report(Would be very useful also please format): No crash dump**

**Comment by THEREALWWEFAN231** [comment]
Yes, i know about this, umm i assume your trying to login with a cracked account?(it currently doesnt work with cracked, its suppose to), if so for now, go to multiplayer and change your name using the name button on the top right(you can change it to anything?)

**Comment by Rex109** [comment]
> Yes, i know about this, umm i assume your trying to login with a cracked account?(it currently doesnt work with cracked, its suppose to), if so for now, go to multiplayer and change your name using the name button on the top right(you can change it to anything?)

Yup, it changes it, but is not chaning my skin. I assume it changes only the name and not the real login?

**Comment by THEREALWWEFAN231** [comment]
Yeah, ull have to wait for 2.8 for that...

**Comment by Rex109** [comment]
> Yeah, ull have to wait for 2.8 for that...

Alright, thanks for the reply. I really hope it will get fixed asap, keep up your work!

**Comment by THEREALWWEFAN231** [comment]
We will keep it open because I haven't actually fixed it yet, but I will later, I won't forget about it if it's open

**Comment by Rex109** [comment]
Alright! I'll keep an eye on it!

**Comment by THEREALWWEFAN231** [comment]
Fixed...
