### ISSUE TITLE
[Suggestion] Illegal Item Bypass

### ISSUE THREAD

**Issue by Vonr** [THEREALWWEFAN231/wwe#261]
**Minecraft Version**
yes

**What is the suggestion**
Make a hack to take items from nearby hoppers and continuously shift the item between the hopper and the first slot of your inventory and another mode for just hopper and inventory. The GUI should not be displayed so users may use illegal items. (I'm decently sure that's how illegal item bypass works but prove me wrong)

**Why it will be useful**
Items like 32k's on 2b2t will be able to be held and other servers with other banned items may be able to be bypassed

**Comment by BleachDrinker420** [comment]
Illegal Itembypass is the exact same code as xcarry so its basically the already in

**Comment by Paralusion** [comment]
thats not how illegalitembypass works, when you activate it, all it does is block 1 packet, which makes it so it doesnt close the hoppers inventory

it'd be cool if when illegalitembypass is on, it only works when you're opening a hopper (so you can leave it on), and when you walk 9 blocks further, it turns off
would be the best illegalitembypass there is

anyway, WWE client is not a client dedicated to 2b2t so I'm not sure if this will happen

**Comment by THEREALWWEFAN231** [comment]
I see what he means, he wants some type of automatic thing, but 32ks are going to be "patched" on 2b2t soon, and 2b2t is the only server in which that bypass works, other anarchy servers actually have it patched correctly, so this is kind of irrelevent
