### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Dryesthalo98066** [THEREALWWEFAN231/wwe#266]
**WWE version:** 
2.7.2
**Minecraft version:** 
1.14.4
**Operating system:** 
windows 10
**Optifine/Other mods:** 

**Whats the issue:** 
When ever i look up or down my game speeds up for me and other players can see it

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
We know about this, it's very weird with weird weird circumstances we haven't fixed it yet, but hope we can in 2.8, for now, you will have to do this,

close minecraft
go to your .minecraft folder, mods wwe.jar
open it with winwar or some type of extaction things
open mixins.wwefan.json
remove "MixinTimer",
save the file, close everything
then start minecraft

**Comment by THEREALWWEFAN231** [comment]
"Fixed" in next update
