### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by AutoKaspersky** [THEREALWWEFAN231/wwe#268]
**WWE version:** 
2.7.2

**Minecraft version:** 
1.12.2

**Operating system:** 
Windows

**Optifine/Other mods:** 
None

**Whats the issue:** 
When getting kicked with the blink module on, you are unable to rejoin multiplayer
or singleplayer servers, they will be stuck loading

**Crash-report(Would be very useful also please format):**
No crash

**Comment by THEREALWWEFAN231** [comment]
This has already been fixed for 2.8, when it releases.

**Comment by AutoKaspersky** [comment]
> 
> 
> This has already been fixed for 2.8, when it releases.

Alright, thanks
