### ISSUE TITLE
Autofarm modes

### ISSUE THREAD

**Issue by BlackVoidMIke** [THEREALWWEFAN231/wwe#276]
**Minecraft Version**
1.13.2+
**What is the suggestion**
Ability to select modes (bonemeal only, place crop only, break crop only)
**Why it will be useful**
It will allow you to fully bonemeal a farm before breaking all the crops with a fortune tool

**Comment by THEREALWWEFAN231** [comment]
Auto farm already does this, if you hold bone meal it will use it, if you hold seeds/carrots or what ever it will place them, if you arent holding thoses it will break fully grown crops(i heard it doesnt work in 1.14 so that will have to be checked out)
