### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by ghost** [THEREALWWEFAN231/wwe#28]
**Minecraft Version**
ALL
**What is the suggestion**
Add Discord Rich Presence for WWE, enabled **by default**
![image](https://user-images.githubusercontent.com/27324728/59866413-82f55780-9359-11e9-932b-3a1e4a4b3726.png)
![image](https://user-images.githubusercontent.com/27324728/59866420-8688de80-9359-11e9-9e97-d947a69101f1.png)

**Why it will be useful**
Free advertising, also rich presence looks cool.

**Comment by Nhjb1** [comment]
I don't think this is a good idea because I play on a lot of small survival servers. If I were to join their discord servers then they could see me using this client on their servers all the time

**Comment by THEREALWWEFAN231** [comment]
I have thought of this many times before but due to me not wanting the extra libraries and dll files in the jar, it currently will not be added.

**Comment by THEREALWWEFAN231** [comment]
https://github.com/jagrosh/DiscordIPC

**Comment by 2b2tQueueProject** [comment]
@Nhjb1 it would be a module that's enabled by default. You can easily turn it off if you want.

**Comment by THEREALWWEFAN231** [comment]
Maybe ill add options to it some other time, but it will be in the next update
