### ISSUE TITLE
Suggestion: Add function so you can recolor ChestESP

### ISSUE THREAD

**Issue by Exaflar** [THEREALWWEFAN231/wwe#281]
**Minecraft Version**
1.12.2
**What is the suggestion**
Add a setting in the color menu to change the specific colors storage units have in ChestESP, inpersonally want chests to be blue instead of yellow but i can't change that in the color menu.
**Why it will be useful**
It's a generally nice thing to be able to customise things. This definitely isn't needed but would be a nice thing to add

**Comment by THEREALWWEFAN231** [comment]
This is in the discords todo, "Add ability to change colors of "everything" before next major update :x:" i will close this when its added, its already ready to be added, but hasent been added yet
