### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by brcndon** [THEREALWWEFAN231/wwe#283]
**Minecraft Version**
Maybe any
**What is the suggestion**
Add an item magnet mod by possibly spoofing player location (no idea if this is possible). also perhaps using it to grab items through walls
**Why it will be useful**
Being able to pick up item further away from you makes looting quicker,other from that idk

**Comment by THEREALWWEFAN231** [comment]
Will only work on vanilla to a certain extent
