### ISSUE TITLE
[Bug] Notebot Realms

### ISSUE THREAD

**Issue by TheBacc** [THEREALWWEFAN231/wwe#291]
**WWE version:** 2.7.2
**Minecraft version:** 1.14.4
**Operating system:** WIndows 10
**Optifine/Other mods:** Optifine

**Whats the issue:** 
On a Minecraft Realm, the notebot mod's tuning feature tunes one noteblock forever. i was doing 5x5 and worked fine on a singleplayer world but not a realm.
**Crash-report(Would be very useful also please format):**
does not cause game crash

**Comment by THEREALWWEFAN231** [comment]
I believe this is fixed, ill have to check later
