### ISSUE TITLE
Bug Color Manager "Version" misspelled

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#297]
**WWE version:** 
all
**Minecraft version:** 
doesnt matter
**Operating system:** 
doesnt matter
**Optifine/Other mods:** 
doenst matter
**Whats the issue:** 
https://i.imgur.com/gCasXB3.png
"WWE Verison 2.7.2" + OverWorld should be Overworld
**Crash-report(Would be very useful also please format):**
does not matter

**Comment by THEREALWWEFAN231** [comment]
I already fixed this in 2.8, I believe.
