### ISSUE TITLE
.prefix doesn't start with the correct character

### ISSUE THREAD

**Issue by d1gress** [THEREALWWEFAN231/wwe#300]
**WWE version:** 
2.7, 1.14.4

**Minecraft version:** 
1.14.4

**Operating system:** 
windows 10

**Optifine/Other mods:** 
literally doesnt matter but i have tried with just wwe

**Whats the issue:** 
lets say i do .prefix ;
then i press ;
chat opens, but it starts with a .
**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Fixed
