### ISSUE TITLE
Realm Crash Bug

### ISSUE THREAD

**Issue by Aquicy** [THEREALWWEFAN231/wwe#301]
If you have the Hud Option "Ping" enabled before or after you join a minecraft realm, the game will immediately crash until you disabled it somewhere else, like in Singleplayer

ill attach a crash report if that helps also
[crash-2019-09-13_01.28.54-client.txt](https://github.com/THEREALWWEFAN231/wwe/files/3609077/crash-2019-09-13_01.28.54-client.txt)

**Comment by THEREALWWEFAN231** [comment]
This has already been fixed for when 2.8 releases
