### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Aquicy** [THEREALWWEFAN231/wwe#303]
2.7.2 
1.14.4
Windows 10
no additional mods other than the required fabric

The waypoint mod glitches all esp mods and makes them solid colors, making it hard to see what is what without turning it off (i.e. a crafting table and furnace both are solid gray in esp, next to each other they look like a chest because the solid colors combine

**Comment by THEREALWWEFAN231** [comment]
Yes i know about this, there is at least one more issue already open about this, i would fix it, if i could replicate it. i cant even with a screen shot lmao, ima close this because theres already a issue or two open
