### ISSUE TITLE
Suggestion - Add TheAltening to WWE

### ISSUE THREAD

**Issue by Xevier1** [THEREALWWEFAN231/wwe#305]
**Minecraft Version**
All/Client wide
**What is the suggestion**
I suggest that you incorporate TheAltening's (https://thealtening.com) public API into the client. TheAltening is a smart minecraft account generator with amazing perks that allow you to use tokens instead of normal alts to login to minecraft. 

They have a very feature packed API that allows it to be implemented into hacked client alt managers for ease and convenience. 

You can view the Java API here https://github.com/TheAltening/TheAlteningAuth4j
and the HTTP API here https://panel.thealtening.com/#dashboard

**Why it will be useful**
TheAltening is already partnered with some of the biggest hacked clients in the game, such as Exhibition, Remix, LiquidBounce, ZeroDay, Aristois, Moon, Astolfo, Osmium, and soon Impact & Future

. It is an incredibly popular website with very professional staff. This would make the client a lot better because it would be much easier to switch alts in-game when you support their authentication libraries.

 Additionally, the staff give out coupon codes to partnered client's users so therefore we would be able to get alts to use for a cheaper price.

**Comment by THEREALWWEFAN231** [comment]
Very interesting

**Comment by rushercrack** [comment]
as someone who has used this service before with tools like oq.Minebot, I very much suggest implementing this into WWE as it is an amazing service. Also, if you're adding this, it'd only be fair to also add the mcleaks api to it which would be accessible for free.

**Comment by THEREALWWEFAN231** [comment]
Added very cool, thank you for the suggestion
