### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by trueblue222** [THEREALWWEFAN231/wwe#307]
no idea
1.14.4
Windows 10
Litematica 

Whenever I try to use WWE, the chest and mob ESP diplay opaque grey boxes instead of the ESP.

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Turn off way points, i can seem to replicate it so i cant fix it, ill try some time again to fix it, feel free to reopen if you have questions or anything.
