### ISSUE TITLE
Suggestion Vanish detector

### ISSUE THREAD

**Issue by TordyCapz** [THEREALWWEFAN231/wwe#312]
**Minecraft Version**
1.14.4
**What is the suggestion**
Detect when a player goes to vanish mode
**Why it will be useful**
For those of us who use hacks in game modes such as survival, it would be great to know when we are in danger of being detected.

**Comment by rushercrack** [comment]
literally told you in discord its not possible

**Comment by TordyCapz** [comment]
> literally told you in discord its not possible

I told in discord:
"It is impossible?"

And you aswered:
"No"

So, you don't told me that its not possible

**Comment by THEREALWWEFAN231** [comment]
He may have said that but you deleted it too, so i wouldn't eb to sure about that

**Comment by THEREALWWEFAN231** [comment]
nvm you dident delete it but yeah
