### ISSUE TITLE
Suggestion turn off blink when leaving

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#315]
**Minecraft Version**
all
**What is the suggestion**
Turn off Blink when exiting the game or leaving a server + make it display a warning when Blink has been on for longer than two minutes
**Why it will be useful**
people are too dumb

**Comment by THEREALWWEFAN231** [comment]
I already had a different fix, but i also added that, nothing wrong with both, also added a chat message when its been on for two minutes and  it turns off
