### ISSUE TITLE
Suggestion GUI's for stuff

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#316]
**Minecraft Version**
all
**What is the suggestion**
make a GUI for Spammer, remove Annoyer and make %player% an attribute in spammer, make a GUI for AutoSign which displays an actual sign where you can type whatever. Merge spammer & chatbot. 
**Why it will be useful**
people are too dumb to use .txts

**Comment by rushercrack** [comment]
Merge Announcer into Spammer

**Comment by rushercrack** [comment]
Merge Join Leave msgs into Spammer

**Comment by rushercrack** [comment]
Inventory Cleaner should also have a GUI

**Comment by THEREALWWEFAN231** [comment]
Most/all in 3.0?
