### ISSUE TITLE
Suggestion Presets & GUI merge

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#318]
**Minecraft Version**
All
**What is the suggestion**
Merge Presets & Click GUI into one category called "client", also add Hud into it.
Merge Color List, Custom Font & Hud into one module
**Why it will be useful**

**Comment by THEREALWWEFAN231** [comment]
Click gui is going into render, color list was moved into hud, as of RIGHT now custom font is not moving, but its very possible that it will
