### ISSUE TITLE
Suggestion Make it possible to toggle without having to use _

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#319]
**Minecraft Version**
All
**What is the suggestion**
Example:
Now: .toggle entity_ride
Then: .toggle entityride
Also: .toggle entity ride
**Why it will be useful**
Gives three options, prevents me from typing the wrong 3000 times

**Comment by THEREALWWEFAN231** [comment]
Considering there is a "command helper" no, because say someone uses spaces, they wont be able to do that with the bind command, its just not a good idea
