### ISSUE TITLE
Suggestion Merge Elytra + and Elytra Replace

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#320]
**Minecraft Version**
All
**What is the suggestion**
Merge Elytra + and Elytra Replace into one module
**Why it will be useful**

**Comment by THEREALWWEFAN231** [comment]
As of right now its going to stay the same, i dont like the idea of moving it to elytra+, i understand it, but elytra + is movement, i was thinking of moving it to auto armor but as of right now im not going to do that, although i think i will in the future
