### ISSUE TITLE
Suggestion Rename Elytra + to Elytra Plus

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#321]
**Minecraft Version**
All
**What is the suggestion**
Rename Elytra + to Elytra Plus
**Why it will be useful**
Having a sudden + in the modules name makes it confusing

**Comment by rushercrack** [comment]
Also change Fancy Chat+ to Fancy Chat, as having this many options for fancy chat is normal nowadays

**Comment by THEREALWWEFAN231** [comment]
I like the + sign... but fancy chat got renamed
