### ISSUE TITLE
Suggestion Add animations

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#328]
**Minecraft Version**
All
**What is the suggestion**
When turning on a module, it should slide into the module list, and when turning it off it should slide out. 
Coordinates being here: https://i.imgur.com/btuQqVj.png is handy and looks nice, but making the chat & coordinates slide up would make it look even cooler.
Also, make an option for coordinates being placed where I just showed, and other information elsewhere
**Why it will be useful**
Looking fancy

**Comment by THEREALWWEFAN231** [comment]
Im working on the module animation right now, personally i dont care for it as to why im adding a option for it, but i really dont like the idea of the chat animation ill see about a animation for it idk

**Comment by rushercrack** [comment]
I'll make a video of how it looks (Future has it), and if you're already working on animations, it'd be cool to be able to control what is animated & what is not, and if possible, something that'd be really awesome is if you can control how long the animation can be. 

warning: music
https://youtu.be/DWKc9oF2byM

**Comment by THEREALWWEFAN231** [comment]
In 3.0
