### ISSUE TITLE
Suggestion Merge NoBreakDelay and SpeedMine

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#330]
**Minecraft Version**
All
**What is the suggestion**
Merge them into one module
**Why it will be useful**

**Comment by THEREALWWEFAN231** [comment]
I dont like this either, because speed mine also "does" no breakdelay, so having a no break delay option would be unless or if it was like this it would be dumb
Speed Mine, Module
	Mine
	No Break Delay
I think thats dumb

**Comment by rushercrack** [comment]
i mean, in speedmine, have an option for normal, and nobreakdelay, or both
