### ISSUE TITLE
Suggestion Remove Color Signs

### ISSUE THREAD

**Issue by rushercrack** [THEREALWWEFAN231/wwe#333]
**Minecraft Version**
All
**What is the suggestion**
Color Signs was patched in 1.13+
**Why it will be useful**
Patched even on Vanilla

**Comment by THEREALWWEFAN231** [comment]
Vanilla mode is not patched, just tested it on 1.14, although wwe with vanilla mode was buggy, i knew this, but just fixed it, it would only edit the top line
