### ISSUE TITLE
Going down ladders glitches out WWE

### ISSUE THREAD

**Issue by itsGalaxy** [THEREALWWEFAN231/wwe#334]
**_WWE version:_** 2.7.2 
**_Minecraft version:_** 1.12.2
**_Operating system:_** Windows 10 
**_Optifine/Other mods:_** Yes OptiFine

Going down ladders puts the player in some sort of floating mode. Whenever you move or turn around you get glitched back to the same place. The problem still persists after relaunching the client and applies to both singleplayer and multiplayer. The only way I have found to fix this is to uninstall and reinstall but I don't want to have to resort to that every time I go down a ladder.

**_Crash-report:_** Game didn't crash so yea.

**_Edit:_** I disabled each module 1 by 1 and found out that it was an issue with the 'Portal' module.

**Comment by THEREALWWEFAN231** [comment]
This was known, its now fixed, its appreciated that you figured out it was portal, so i dident think it was another problem.
