### ISSUE TITLE
Suggestion | Notebot Looping

### ISSUE THREAD

**Issue by khubik** [THEREALWWEFAN231/wwe#335]
**Minecraft Version** - 1.12.2

**What is the suggestion** - add an option to toggle looping modes; repeat one song, repeat entire song list, shuffle, and none.

**Why it will be useful** - nice and easy 2b2t antiafk solutions, also these are essential features for any music player.

**Comment by rushercrack** [comment]
cool suggestion especially for the new note bot :)
