### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ImSwordKing** [THEREALWWEFAN231/wwe#336]
**Minecraft Version**
All
**What is the suggestion**
Tells you when an update is out
**Why it will be useful**
because people don't know when an update is out and don't update

**Comment by THEREALWWEFAN231** [comment]
Yes, im working on a screen for that, on the wwe main menu it tells you if theres a update out, not anywhere else though, thats where this screen im making will help

**Comment by THEREALWWEFAN231** [comment]
In 3.0
