### ISSUE TITLE
Suggestion - disable hacks from main menu

### ISSUE THREAD

**Issue by bjcband** [THEREALWWEFAN231/wwe#337]
**Minecraft Version**
1.12.2 latest wwe (1 week ago)
**What is the suggestion**
allow to disable text spam/hacks altogether from the main menu
**Why it will be useful**
because if you accidentally set it to the fastest setting, you can get kicked for spam, and not join back as the hacks are active

**Comment by rushercrack** [comment]
would be better if it automatically turned off after exiting/disconnecting

**Comment by THEREALWWEFAN231** [comment]
Already have it planned to be able to open the click gui from wwe settings

**Comment by THEREALWWEFAN231** [comment]
In 3.0
