### ISSUE TITLE
Bug Report - keybind addition not closing

### ISSUE THREAD

**Issue by bjcband** [THEREALWWEFAN231/wwe#338]
**WWE version:** 
latest (pretty sure)
**Minecraft version:** 
1.12.2-1.14.4
**Operating system:** 
win10
**Optifine/Other mods:** 
optifine and fps+ 
**Whats the issue:** 
If you click 'set keybind' on a hack and then close the menu, if you open it, it stays as 'waiting' forever and you have to set it to something
**Crash-report(Would be very useful also please format):**
nothing crashed

**Comment by THEREALWWEFAN231** [comment]
click it again, suppose ill make it remove that when closing the gui

**Comment by THEREALWWEFAN231** [comment]
Confusing to explain, but its fixed in the next version, if it wasent working 🤷‍♀
