### ISSUE TITLE
Lag while toggling modules

### ISSUE THREAD

**Issue by ghost** [THEREALWWEFAN231/wwe#34]
**WWE version:** 
latest

**Minecraft version:** 
ALL

**Operating system:** 
Windows 10 64 bit

**Optifine/Other mods:** 
KAMI

**Whats the issue:** 
Every time you toggle a module, the entire game freezes for a bit. Might be related to the WWE Settings saving system?

**Crash-report(Would be very useful also please format):**
none

**Comment by IAmWolfie** [comment]
I don't have this issue?

**Comment by mememasterlord32345** [comment]
I don't have this issue

**Comment by 2b2tQueueProject** [comment]
it freezes for a bit. Maybe like 0.2s

**Comment by Paralusion** [comment]
Try to create a new .minecraft folder (backup your old one) and see if the lag still remains with only WWE installed.

**Comment by Paralusion** [comment]
no response within 14 days, this can be closed
