### ISSUE TITLE
Full bright free cam

### ISSUE THREAD

**Issue by itsGalaxy** [THEREALWWEFAN231/wwe#340]
**WWE version: 2.7.2** 
**Minecraft version: 1.12.2** 
**Operating system: Windows 10** 
**Optifine/Other mods: OptiFine** 

**Whats the issue: When entering freecam, the module Fullbright disables** 

**Crash-report(Would be very useful also please format): No crash report**

**Comment by THEREALWWEFAN231** [comment]
This did not happen for me, considering you said "the module Fullbright disables" maybe you had them bound to the same key 🤷‍♂
