### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Vampire94937** [THEREALWWEFAN231/wwe#347]
**Minecraft Version**
1.14.4
**What is the suggestion**
More "Ridgid" flying. As in, if you stop pressing the key, you stop moving, you don't carry any velocity like in creative mode. (Like in Wurst)
**Why it will be useful**
More precise movements, makes you take off faster because you have to wait for it to smooth into the speed you set it to instead of it just going at that speed.

**Comment by THEREALWWEFAN231** [comment]
Added in 3.0
