### ISSUE TITLE
Layer related modules break when shader is activated.

### ISSUE THREAD

**Issue by TheGhost567** [THEREALWWEFAN231/wwe#350]
Latest version as of 9-10-2019
1.14.4
Windows 10 64 bit
OptiFine_1.14.4_HD_U_F2, shader, of course. 

Modules related to layers (edges, holograms, anything that shows through blocks and outlines an object(Not tracers)) break under the effect of a shader, this is most likely caused by the shader changing shadow and lightmaps, like outline esp messing up layering (like the two layers of a skin clipping and showing through eachother), or rainbow enchant messing with reflections to the point that it is blinding to look at.

No crash report as it is a lighting issue.

**Comment by Paralusion** [comment]
not a WWE issue, try putting a potion of outlining or whatever on a person and using a shader

**Comment by TheGhost567** [comment]
> not a WWE issue, try putting a potion of outlining or whatever on a person and using a shader

sorry i was unaware, i'll try looking more into issues before i submit them

**Comment by THEREALWWEFAN231** [comment]
Its all good, the shaders usually change alot of stuff, and isent really easily fixable like at all
