### ISSUE TITLE
It wont download

### ISSUE THREAD

**Issue by chazdsth** [THEREALWWEFAN231/wwe#352]
*1.12.2 forge
1.12.2 
**Operating system:** ?
**Optifine/Other mods:** ?
![notepad_it9NcNjEUh](https://user-images.githubusercontent.com/55357431/67227283-dc1be780-f42e-11e9-8756-ae0fc37abbae.png)

The download doesnt work

It just comes up with a blank pagw

**Comment by THEREALWWEFAN231** [comment]
Exit and keep clicking get link till it works, you have to re wait 5 seconds because it has been 16 minutes
