### ISSUE TITLE
Chest Esp is not working well.

### ISSUE THREAD

**Issue by KemalUzn** [THEREALWWEFAN231/wwe#358]
WWE version:
2.7.2

Minecraft version:
1.14.4

Operating system:
Windows 10

Optifine/Other mods:
Optifine
Block Meter
Custom Selection Box
MiniHUD
Mod Menu
Mouse Wheelie
Orderly
Shulker Box Tooltip
VoxelMap

Whats the issues:
When I select CHESTS in Chest Esp, its not rendering anything.
When I select DISPANSER, both Dispanser and Dropper are rendering.

[This is the video of bug](https://youtu.be/FaU6OzVKGek)

**Comment by THEREALWWEFAN231** [comment]
Chest esp completely changed in the upcoming update, i fixed "When I select DISPANSER, both Dispanser and Dropper are rendering." im sure i fixed everything else too

**Comment by KemalUzn** [comment]
You're the best!
