### ISSUE TITLE
Autofish bug (probably) cause game holding right click.

### ISSUE THREAD

**Issue by vungsung** [THEREALWWEFAN231/wwe#370]
**WWE version:** 3.0
**Minecraft version:** 1.14.4
**Operating system:** Windows 10 1903
**Optifine/Other mods:** None
**Fabric loader version:** 0.7.2

**Whats the issue:** 
When enabled `Autofish`,  Minecraft client holds `Right Click` all the time. So when you point your mouse at a box, you won't be able to close the box or call out the ESC menu since the box reopens instantly right after you close the box, unless you forcibly move your mouse across a long distance to make the view not pointed to the box. Same as the door, it keeps open and close when you point at them.

**Comment by THEREALWWEFAN231** [comment]
Lol, probably should check if they are holding a fishing rod, ok, ill fix this later

**Comment by vungsung** [comment]
You mean the other players near me holding fishing rod might cause this? lol
I was in a house, while all other players in a few chucks away tho, but I'm not sure if the admin teleported around me. Anyway just a note.

**Comment by vungsung** [comment]
Confirmed fixed, thank you.
