### ISSUE TITLE
autocomplete not usable at .b follow [playerName]

### ISSUE THREAD

**Issue by vungsung** [THEREALWWEFAN231/wwe#371]
**WWE version:** 3.0
**Minecraft version:** 1.14.4
**Operating system:** Windows 10 1903
**Optifine/Other mods:** None
**Fabric loader version:** 0.7.2

**Whats the issue:** 
`.b follow` followed by `tab` not showing any players, not either fills in data. So you have to type the fullname of that player.

**Comment by entity493** [comment]
That is a baritone issue you may make an issue here https://github.com/cabaletta/baritone/issues
Or if it is a client issue use the # prefix instead Example `#follow {name}`

**Comment by vungsung** [comment]
`#follow` works, but `.b follow` doesn't
In the 2.x version of WWE the `.b follow` worked. So it's due to Baritone itself not WWE? Thank you
