### ISSUE TITLE
Suggestion server menus have timer enabled

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#378]
**WWE version:** 
3.0.1
**Minecraft version:** 
1.14.4 was used, but may occur on all versions
**Operating system:** 
Linux
**Optifine/Other mods:** 
only WWE

**Whats the issue:** 
Server menu items (direct connect, add server) have timer enabled
**Crash-report(Would be very useful also please format):**
Not needed

**Comment by THEREALWWEFAN231** [comment]
Made timer not work on menus, also tried to fix the timer bug again...
