### ISSUE TITLE
better nuker

### ISSUE THREAD

**Issue by FarmerJoe2b2t** [THEREALWWEFAN231/wwe#38]
1.12.2

make selective nuker swap to the best tool in your hotbar, or add a separate hopper nuker like what rusherhack has

you can have it on constantly and you won't have to swap tools, and it will be harder for people to 32k you

**Comment by THEREALWWEFAN231** [comment]
You could use auto tool, and if you turn off option All Blocks and turn on option Hopper, it will break hoppers
