### ISSUE TITLE
Grey HUD

### ISSUE THREAD

**Issue by thePigBoss1** [THEREALWWEFAN231/wwe#383]
The HUD is grey and fuzzy while in the queue of 2b2t. When the spectator menu is up its fine.

<img width="966" alt="Screen Shot 2019-11-30 at 9 11 01 PM" src="https://user-images.githubusercontent.com/58378588/69908436-71f44c00-13b7-11ea-8afb-8e2b99ba8fe8.png">
<img width="966" alt="Screen Shot 2019-11-30 at 9 14 28 PM" src="https://user-images.githubusercontent.com/58378588/69908437-7587d300-13b7-11ea-9bde-445cda72439c.png">

**Comment by THEREALWWEFAN231** [comment]
Bleach said in the discord turn off fast render, options video settings, performance, fast render, that appears to cause it, mine dident get as gray as your but yeah i think fast render causes that
