### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by smertnix55551** [THEREALWWEFAN231/wwe#386]
**WWE version:** - 3.0.1
**Minecraft version:** - 1.12.2
**Operating system:**  - Windows
**Optifine/Other mods:** - No

**Whats the issue:** 
when you right-click on a player with a shield you will crash from the server.
Pls fix it!
ip: Play.jetmine.ru mc.prostocraft.net

**Crash-report(Would be very useful also please format):**
![Screenshot_1](https://user-images.githubusercontent.com/54067500/69911491-043f3300-143e-11ea-9dab-7b887415f786.png)

VIdeo: https://www.youtube.com/watch?v=5Me26fIV_-M&feature=youtu.be

**Comment by THEREALWWEFAN231** [comment]
No slow down, send the server ip please.
