### ISSUE TITLE
Autofish on drug

### ISSUE THREAD

**Issue by vungsung** [THEREALWWEFAN231/wwe#391]
WWE version: 3.0.0 - 3.0.2
Minecraft version: 1.14.4
Operating system: Windows 10 1903
Optifine/Other mods: None
Fabric loader version: 0.7.2

**Whats the issue:** The **Autofish** somehow keeps rethrowing out the fish rod on specific server.
Video: https://www.youtube.com/watch?v=LDWSSGv5Km0
This issue did not occur in Singleplayer.

**Server Information:**
Server: PaperSpigot 1.14.4 (build 2019.12.1)
Plugins: WorldGuardian, SkinRestorer, WorldEdit all running latest version.
Online mode: Off

After waiting a few days it still happens. Looking for other users if they are facing the same problem.
I didn't try it on other servers, I'll try to test it asap.

**Comment by vungsung** [comment]
Update: today i tested on another server, same running PaperSpigot 1.14.4, with no plugins. The server is much less lag (-50ms). It's still twitching, but with less frequency, not like the previously one showed in the video.
I guess I'm going to jdgui the code cus I don't know any other way to investigate the encrypted packets...

**Comment by THEREALWWEFAN231** [comment]
It needs a delay mode....

**Comment by vungsung** [comment]
Oh yes, you are so smart! Now I see why it previously worked on my localhost server and singleplayer..
