### ISSUE TITLE
Bug. ESP stops working after /tp 

### ISSUE THREAD

**Issue by fuckmymom771** [THEREALWWEFAN231/wwe#393]
**WWE version:** 3.0.x
**Minecraft version:** 1.14.4
**Operating system:** Windows 7
**Optifine/Other mods:** none

**Whats the issue:** 
Sometimes EPS breaks after teleporting. I was able to reproduce this bug by teleporting a few thousands blocks away with ESP enabled. But that doesn't occur every time, you may need several attempts.
Also I was able to break ESP by constantly changing render distance. I guess this is the same bug because it behaves same way.

**Crash-report:**
[crash-2019-12-04_01.32.10-client.txt](https://github.com/THEREALWWEFAN231/wwe/files/3919512/crash-2019-12-04_01.32.10-client.txt)

**Comment by THEREALWWEFAN231** [comment]
Ok, thanks for the extra information

**Comment by THEREALWWEFAN231** [comment]
I am unable to replicate this, im going to close this, maybe its one of your minecraft settings doing it, im not sure, but if you get any new information feel free to reply

**Comment by fuckmymom771** [comment]
Outline mode. Looks like every other mode is fine, only outline i buggy.
