### ISSUE TITLE
Bug. FreeCam horizontal speed

### ISSUE THREAD

**Issue by fuckmymom771** [THEREALWWEFAN231/wwe#399]
**WWE version:** 3.0.2
**Minecraft version:** 1.14.4
**Operating system:** Windows 7, Ubuntu
**Optifine/Other mods:** None

**Whats the issue:** 
FreeCam horizontal speed is very low and doesn't affected by .value freecam speed.

**Comment by fuckmymom771** [comment]
Ok, I've reinstalled Minecraft and WWE and problem is gone. Not sure if it reproducible so you might want to close this issue.

**Comment by THEREALWWEFAN231** [comment]
Yeah im going close this, i havent see this, if anyone knows how to cause this, comment and ill check it out
