### ISSUE TITLE
Searcher bug

### ISSUE THREAD

**Issue by Semichaotic** [THEREALWWEFAN231/wwe#4]
**WWE version: 2.5** 
**Minecraft version:1.13.2** 
**Operating system: Win 10** 
**Optifine/Other mods: Optifine** 

**Whats the issue: Searcher doesn't work at all. Tracers & ESP not showing up**

**Comment by THEREALWWEFAN231** [comment]
diid you add the block?, .search add/remove block name redcolor(0-255) greencolor(0-255) bluecolor(0-255), example .search add obsidian 255 255 255, it will show up white
