### ISSUE TITLE
Bug: Jesus Mini Jump mode performs huge jumps

### ISSUE THREAD

**Issue by fuckmymom771** [THEREALWWEFAN231/wwe#400]
**WWE version:** 3.0.2
**Minecraft version:** 1.14.4
**Operating system:** Windowns 7
**Optifine/Other mods:** Optifine

**Whats the issue:** 
Walking into the water with jesus mini jump enabled pushes you 7000 blocks up every second.

**Comment by THEREALWWEFAN231** [comment]
Fixed
