### ISSUE TITLE
Sneak packet mode is on without showing it

### ISSUE THREAD

**Issue by fedddddd** [THEREALWWEFAN231/wwe#410]
**WWE version: 3.0.2
**Minecraft version: 1.15 and 1.14.4 
**Operating system: Windows 10
**Optifine/Other mods: No

**Whats the issue: While sneak packet mode is off other people actually see me sneaking just as if it was actually on.

**Comment by THEREALWWEFAN231** [comment]
I dont not think this is wwe, im going need some sort of proof showing its wwe... feel free to comment

**Comment by fedddddd** [comment]
Im not even sure myself but people told me i was running/walking while sneaking and loading vanilla client seemed to fix it
