### ISSUE TITLE
[Bug] Trident boost crash

### ISSUE THREAD

**Issue by Rasputing** [THEREALWWEFAN231/wwe#412]
**WWE version:** 1.14.4
**Minecraft version:** 1.14.4
**Operating system:** windows
**Optifine/Other mods:** no other mods

**Whats the issue:** When i try to use trident boost mc crashes

**Crash-report(Would be very useful also please format):**
Process crashed with exit code -805306369
mc completely deadlocks so no stacktrace

**Comment by THEREALWWEFAN231** [comment]
Oh lord, well it dident "crash" for me but it does not work correctly as it does on 1.13, code was completely messed up :eyes: fixed in next bug fix update
