### ISSUE TITLE
Suggestion: option to turn off x-ray warnings

### ISSUE THREAD

**Issue by blockbandit** [THEREALWWEFAN231/wwe#422]
WWE currently echoes a Fabric/Indigo warning when x-ray is activated on non-Optifine setups. It will be helpful to have an option to turn off this warning as it clutters up the chat.

**Comment by THEREALWWEFAN231** [comment]
This has been added for donators with prebuilds when the next prebuild is released, it will be released for everyone in 3.1. It's a JVM argument, -Ddisablefabricindigomessage=true you will add it to the fabric profile in the Minecraft launcher.
![image](https://user-images.githubusercontent.com/21975901/74197187-c156c400-4c13-11ea-8dce-987d7ef66037.png)
