### ISSUE TITLE
Safe Walk: Edge case

### ISSUE THREAD

**Issue by Gigabitten** [THEREALWWEFAN231/wwe#427]
Literally. I landed on the edge of a block and glitched right the fuck out; disabling safe walk and breaking the block under me didn't help, and I got disconnected after spending a while watching the server and the client fight about my vertical position.

![image](https://user-images.githubusercontent.com/24787321/71623566-bdf30600-2b9a-11ea-9972-0e8e99ff990d.png)

**Comment by Gigabitten** [comment]
With further play, I've realized that anti void *might* have something to do with it.  If CNR with the first message, try in combination with void glide.

**Comment by Gigabitten** [comment]
I was very tired when I wrote that. Void glide is a type of trick in Doom speedrunning. 

Anti-void. I meant anti-void.

**Comment by THEREALWWEFAN231** [comment]
As you said it was Anti Void, when you are falling it teleports you up a bit, usually causing the server to teleport you to your last safe location, but maybe it kicks you on 2b2t, Anti Void will be improved some time, I dont know when though.
