### ISSUE TITLE
maybe Bug packet fly and most thing like that cause damage

### ISSUE THREAD

**Issue by oiirn29** [THEREALWWEFAN231/wwe#434]
**WWE version:** 3.0.4
**Minecraft version:** 1.14.4 and 1.12.2
**Operating system:** windose
**Optifine/Other mods:** optifine

**What's the issue:** 
 packet fly and most thing like that cause damage
**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
This isent a "bug" if your in single-player, change y distance to like 5 or something, basically you want your Y Position - Y Distance(setting) to be a block in the ground, for it to work in single-player, on servers you want  y distance to basically be 999

**Comment by oiirn29** [comment]
ok thanks
