### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by thepengvuin** [THEREALWWEFAN231/wwe#438]
**WWE version:**  3.0.4
**Minecraft version:** 1.12.2  (forge)
**Operating system:**  Forge?
**Optifine/Other mods:**  none

**Whats the issue:**   i am stuck but i can move up and down but not to he sides. i have tried to log out and back in turn of all mods and to sleep in a bed to move location but its still the same

**Crash-report(Would be very useful also please format):** idk what that means i am not a nativ

**Comment by THEREALWWEFAN231** [comment]
This isn't really enough information. You said you turned everything off, but I would assume its portal, maybe packet fly but I doubt that, feel free to reopen and or reply.
