### ISSUE TITLE
Crash in combination with WorldDownloader when hitting ESC

### ISSUE THREAD

**Issue by PepeHands78** [THEREALWWEFAN231/wwe#439]
**WWE version:** 3.0.4
**Minecraft version:** 1.12.2
**Operating system:** Windows 10 (64 bit)
**Optifine/Other mods:** Litemod,WorldDownloader

**Whats the issue:** 
1. Install Forge and LiteLoader
2. Install Litemod WorldDownloader version 4.0.6.0
3. Install WWE
4. Launch Minecraft and play in a singleplayer or multiplayer environment
5. As soon as ESC is pressed, the game should crash

**Crash-report(Would be very useful also please format):**

https://pastebin.com/ejpwE8vw

**Additional notes:**
This occurs exactly as the Pause/ESC menu is built, so I assume it has something to do with the button by both WorldDownloader and WWE being created on the screen, one of them is causing a NullPointerException as far as I can read the crash report. It's my favorite client and I'd love to use it. Thanks in advance.

**Comment by THEREALWWEFAN231** [comment]
Send the world downloader mod i dont have it anymore

**Comment by THEREALWWEFAN231** [comment]
This has been fixed donators with prebuilds when the next prebuild is released, it will be released for everyone in 3.1
