### ISSUE TITLE
Suggestion (No baritone build)

### ISSUE THREAD

**Issue by mikumikuyo** [THEREALWWEFAN231/wwe#44]
**Minecraft Version**
1.12.2
**What is the suggestion**
No baritone version
**Why it will be useful**
baritone crashes me on modded minecraft and wwe is a very handy client to have. i also think it might cause memory leaks after mc has been running for a long time

**Comment by THEREALWWEFAN231** [comment]
go to the launcher, go to launch options, go to the profile(in this case the forge one), enable JVM arguments if it isent already and add -Ddisablebaritone=true
