### ISSUE TITLE
NO Sound and no language bug

### ISSUE THREAD

**Issue by tronprogram** [THEREALWWEFAN231/wwe#447]
**WWE version:** 3.0.4
**Minecraft version:** 1.14.4
**Operating system:** Microsoft Windows 10
**Optifine/Other mods:** No

**Whats the issue:** 
The thing is that I recently installed the mod for fabric but when I enter the game it has no sound and if I try to change the language none appears.
I tried to change the texture pack but nothing happened.
![Sin título](https://user-images.githubusercontent.com/60573173/73609015-7bf12180-4597-11ea-9aae-f10e271e786e.png)

**Comment by THEREALWWEFAN231** [comment]
This isn't a WWE bug, id say its more of a fabric bug, but you don't have your Minecraft setup correctly or something, maybe you didn't run vanilla 1.14.4(or you need to rerun it), as you can see some of the textures didn't load, like the game icon, sounds, and languages.
