### ISSUE TITLE
Suggestion: Notebot open minecraft note block studio support

### ISSUE THREAD

**Issue by u5k44x1104** [THEREALWWEFAN231/wwe#448]
**Minecraft Version**
1.15.2

**What is the suggestion**
Support for .nbs files made in open minecraft note block studio

**Why it will be useful**
Well open minecraft note block studio supports new instruments and well it would just be fun to play more instruments i guess...

**Comment by THEREALWWEFAN231** [comment]
In the current prebuild for donations will be released to everyone in 3.1
