### ISSUE TITLE
Suggestion: Notebot legit mode

### ISSUE THREAD

**Issue by u5k44x1104** [THEREALWWEFAN231/wwe#449]
**Minecraft Version**
1.15.2

**What is the suggestion**
Would be nice to have an option for notebot to aim the client at the blocks like with autofarm
**Why it will be useful**
Because it looks stupid when i get multiple clients playing different parts of a song and they just stand there twitching their head would be nice if they actually aimed at the blocks.....

**Comment by THEREALWWEFAN231** [comment]
It aims at the block server side same with auto farm, other people will see you looking at the note blocks, there use to be a thing if you were in 3rd person you could see your self snapping to the blocks but i temporarily removed it.

**Comment by u5k44x1104** [comment]
But i tested it and it just twitched the head for a moment and then the head went back to its original position, watch the left guy at 1:46 https://www.youtube.com/watch?v=V-oA2QBkQr0
Also autofarm has legit mode function which snaps at crops client-side, that's the thing i suggested to add for notebot too... i mean i understand it would still look fishy af with 20 notes per tick but if you use 1 note per tick and suggested legit mode it should look awesome like if your clients were actually playing so concerts would not look so derpy
