### ISSUE TITLE
1.15 donwload?

### ISSUE THREAD

**Issue by luxkas** [THEREALWWEFAN231/wwe#450]
is there still a way to get the minecraft 1,15 version?

**Comment by THEREALWWEFAN231** [comment]
https://wweclient.com/faq.php 

Other 1.13/1.14/1.15 versions
Question: Where can I get the other older versions of the newest minecraft version? Answer: Just install the newest wwe version(load it if you already have it), for example if i want 1.14.1, im going load the newest 1.14.x(4) version of wwe, if i want 1.15 im going load the newest wwe 1.15.x version. Once you have loaded wwe, go to the multiplayer screen and in the top left you will see a button showing your current minecraft version, click it till you see your desired version you want to play, then you can join servers with that version
