### ISSUE TITLE
.vanish command for Trader llamas

### ISSUE THREAD

**Issue by tyrannus00** [THEREALWWEFAN231/wwe#451]
**1.15 and above**

**Add the trader llama to the list of entities the .vanish dismount/remount command works on**

This will enable dupes again because on most servers the llama dupe was fixed by not letting one place the chest on the llama/donkey. Since the trader llama isnt a normal llama that fixed didnt include it, so one is still able to place a chest on a trader llama on a server running paper. The dupe does not durrently work, because the .vanish dismount command isnt working on the trader llama.
If this gets implemented in the next version, it re-enables dupes again and would therefore be very useful.

This was tested on 1.15.2 anarchy server destroymc.net that is running papermc.
Anyways, thanks for the awesome client.

**Comment by THEREALWWEFAN231** [comment]
.vanish does work with trader llamas, I just tried it. Did you try the dupe and it didn't work and assumed .vanish didn't work? I don't know but .vanish is a bit different in 1.14.4+ as I couldn't figure out how to make the code the same/didn't majorly look at it. Feel free to comment and or reopen.
