### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by JOELEQ** [THEREALWWEFAN231/wwe#474]
**Minecraft Version**
1.15.2

**What is the suggestion**
It would be really cool if the WWE client was working with optifine... (specifically Optifabric)

**Why it will be useful**
We could get better performance so the client will be more stabilized and players would have a chance to use shaders and stuff ? i really hope this will go thru.. it would be really helpful. thank you 
-J

**Comment by Paralusion** [comment]
wwe already works with optifine, buy prebuilds

**Comment by JOELEQ** [comment]
oh, could u please send me a link to some? I could not really find one.

**Comment by JOELEQ** [comment]
oh,

**Comment by Paralusion** [comment]
costs money, 20$

**Comment by JOELEQ** [comment]
bruh, that doesn´t make sence at all, what is so special about the prebuild except for the ability to use optifine ? :/

**Comment by Paralusion** [comment]
all sort of things? whenever the developer works on it, he gives donators prebuilds, because they like to get features earlier.

https://wweclient.com/ChangeLog.php
at the top of the page, you'll see the changelog for current prebuild
