### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by memerich** [THEREALWWEFAN231/wwe#482]
hello ı am using 1.12.2 wwe forge mod

my suggestion is how do ı change the modid in mcmod.info thing ı am changing with notepad++ but it is not working pls help me ı need it

ı want to chane id bcs a server has protection like looking mod ids and mod id wwe is blocked on server

**Comment by THEREALWWEFAN231** [comment]
I did say to create an issue but you cant actually change it, its referenced once inside WWEs' code and in the mcmod.info file so that's why it doesn't work, I can add something though that doesn't send it to the server, sometimes, but you will have to wait.

**Comment by memerich** [comment]
so ı cant change it

**Comment by THEREALWWEFAN231** [comment]
In the next prebuild(publically in 3.1) servers won't be notified you are using WWE client.
