### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Ziggy-Dev** [THEREALWWEFAN231/wwe#484]
**Minecraft Version**
Snapshot 20a11w

**What is the suggestion**
Support for snapshot

**Why it will be useful**
Dupe glitch(s)

**Comment by Paralusion** [comment]
this wont happen, it isn't a simple thing to do

**Comment by THEREALWWEFAN231** [comment]
It kind of is easy, especially if you follow the snapshots but this won't be happening for prebuild reasons, I'm not going to explain, but yeah it won't happen.
