### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DoggosGames** [THEREALWWEFAN231/wwe#495]
**WWE version: 3.0.8** 
**Minecraft version: 1.12.2 - Forge 1.12.2-14.23.5.2768/2847** 
**Operating system: Windows 10** 
**Optifine/Other mods: None** 

**Whats the issue: Blinking disconnects me from my singleplayer mode, I don't know the cause of this, I have tried with the recommended version and it still happens, I've tried allocating more RAM and it still happens.** 

**Crash-report(Would be very useful also please format): There's no crash report, it only disconnects me from my world.**

**Comment by Paralusion** [comment]
Blink is not supposed to work on singleplayer

**Comment by THEREALWWEFAN231** [comment]
Just a bit faster than me I see.

**Comment by DoggosGames** [comment]
> Blink is not supposed to work on singleplayer

Oh god I'm fucking stupid.
