### ISSUE TITLE
unable to use Baritone

### ISSUE THREAD

**Issue by DoggosGames** [THEREALWWEFAN231/wwe#497]
**WWE version: 3.0.4** 
**Minecraft version: 1.15.2 - Fabric loader 0.8.2** 
**Operating system: Windows 10** 
**Optifine/Other mods: N/A** 

**Whats the issue: I can't seem to be able to use baritone, I've tried both of the prefixes for it (# and .b). Was it removed or is it conflicting with other WWE versions?** 

**Crash-report(Would be very useful also please format): N/A**

**Comment by Paralusion** [comment]
as listed on the homepage, 1.15.2 doesnt support baritone

**Comment by THEREALWWEFAN231** [comment]
Baritone isent in the 1.15 version of wwe yet, it will be in 3.1
