### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by NukeFromNK** [THEREALWWEFAN231/wwe#498]
**WWE version: 3.0? Idk it's the latest** 
**Minecraft version:1.12.2** 
**Operating system:Win10** 
**Optifine/Other mods:no** 

**Whats the issue:When I try to enter a server its all good but then appears "Loading Terrain" and then the game crashes and returs to launcher, and appears an error** 

**Crash-report(Would be very useful also please format):soory i dont know whats that**

**Comment by Paralusion** [comment]
if you're not willing to share the WWE version and crash report with us, we're unable to help you

**Comment by THEREALWWEFAN231** [comment]
You need to send you crash report, go to your .minecarft folder, crash-logs, its probably the newest file.

**Comment by NukeFromNK** [comment]
I know but there isnt anything from today, and when the game crashes doesn't appear any error code, just a message saying "an unexpected error ocurred (etc.)" I could screen record it if you want

**Comment by THEREALWWEFAN231** [comment]
Yes please.

**Comment by NukeFromNK** [comment]
Wait it works fine now, i reinstalled it. Sorry to waste your time guys but thanks for replying fast!

**Comment by THEREALWWEFAN231** [comment]
All good, glade it works.
