### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by SkullyFX** [THEREALWWEFAN231/wwe#500]
**WWE version:*3.0.4* 
**Minecraft version:*1.15.2* 
**Operating system:*Windows 10 64 bit* 
**Optifine/Other mods:*Optifine/OptiFabric* 

**What's the issue:* WWE Doesn't work with OptiFabric, which is frustrating me because whenever I don't use Optifine I have 3-10 FPS and with Optifine I get at least 40-80 FPS* 

**Crash-report(Would be very useful also please format):*https://pastebin.com/zPu6E1MA *

**Comment by THEREALWWEFAN231** [comment]
In 3.1 this is fixed.

**Comment by SkullyFX** [comment]
Ok thanks, Just out of interest about how long will I have to wait?

**Comment by SkullyFX** [comment]
> In 3.1 this is fixed(you will have to wait till its released).
Ok thanks but just out of interest how long will I have to wait?

**Comment by THEREALWWEFAN231** [comment]
Theres no release date set, but if you really want to use OptiFine now you can do this
1. Open the wee 1.15.2 jar in winwar
2. Open the file called mixins.wwefan.optifine.json in like notepad or something
3. remove line number 8, it has this     "MixinOptifineBlockModelRenderer"
4. save the file
5. In winwar select update archive
6. Load WWE with Optifine
Keep in mind x-ray wont work with optifine, ill see about fixing it some other time

**Comment by SkullyFX** [comment]
Well I did it, but it doesn't seem to work.

**Comment by SkullyFX** [comment]
Oh nvm, I did it wrong, it worked now, thx
