### ISSUE TITLE
MCPE hacks Suggestion

### ISSUE THREAD

**Issue by Unbatedivy79643** [THEREALWWEFAN231/wwe#507]
** Bedrock edition **

**WWE client for MCPE **

**Well for mobile users like me i want to use my WWE hacks on mobile i might add some concept images bellow and yeah so make it a ios and android friendly thing by macking it do render hacks not like pvp hacks and make so its no jailbreak or root by macking it a .mcpack resource pack thing **

                                                          Concept images bellllow
![unnamed (6)](https://user-images.githubusercontent.com/64863069/81201778-92a37c00-8fbd-11ea-9cb0-c4a990cc38d6.jpg)
![unnamed (7)](https://user-images.githubusercontent.com/64863069/81201801-9afbb700-8fbd-11ea-85c6-d7a56d88cd68.jpg)
![unnamed (8)](https://user-images.githubusercontent.com/64863069/81201832-a3ec8880-8fbd-11ea-9ec1-190dd3f9b5eb.jpg)
![unnamed (9)](https://user-images.githubusercontent.com/64863069/81201845-a949d300-8fbd-11ea-8752-75b43c3d975b.jpg)

**Comment by THEREALWWEFAN231** [comment]
WWE isent a hack/has hacks, it has player utilities. "yeah so make it a ios and android friendly thing by macking it do render hacks not like pvp hacks and make so its no jailbreak or root by macking it a .mcpack resource pack thing", firstly I don't know really anything about texturepacks/addons for MCBE, so I probably couldn't do that, I have thought of a windows 10 mod but currently that's too much of a pain, I don't think ill ever do any type of pocket edition mod.

**Comment by Unbatedivy79643** [comment]
Oh i thought WWE client was a hacker client and 2 if you can mabye try to get some help of macking it cuz im bad at that stuff to
