### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ReallyPositive** [THEREALWWEFAN231/wwe#509]
**1.12.2**

**nether portal tracers**

**this will be easy to find portals that lead to bases..? idk**

**Comment by Paralusion** [comment]
use BlockESP

**Comment by ReallyPositive** [comment]
how can i add the block "nether portal"? or do i just have to do obsidian? because i also want to use it in the overworld

**Comment by THEREALWWEFAN231** [comment]
.blockesp add portal, theres also .blockesp gui, which is easier to manage.
