### ISSUE TITLE
Suggestion [Notebot + Reach]

### ISSUE THREAD

**Issue by watermelonboi420** [THEREALWWEFAN231/wwe#513]
**Minecraft Version**
All
**What is the suggestion**
You could add the support for the "reach" module in the notebot, so we could reach farther noteblocks, consequently we could build bigger pianos and use all the instruments in the game at the same time, without changing piano for every song.
**Why it will be useful**
We could play so many songs without editing or changing the piano, because the one we would use would be a lot bigger, allowing presence of more instruments.

**Comment by watermelonboi420** [comment]
Also, I tried to toggle reach and notebot in tune mode at the same time, but I think the bot recognises only the blocks you can reach in vanilla minecraft, so it doesn't even try to tune farther blocks

**Comment by THEREALWWEFAN231** [comment]
Note Bot mode Per song literally maxes out the reach, I like its like 6 blocks in each direction(not up and down), which in most cases you cant even reach because Minecraft doesn't allow it. Feel free to reply if you have a question.
