### ISSUE TITLE
Suggestion XRAY chat flood

### ISSUE THREAD

**Issue by Zasty** [THEREALWWEFAN231/wwe#514]
**Minecraft Version**
1.15.2
**What is the suggestion**
Button to disable xray advertisement on chat
**Why it will be useful**
is very uncomfortable see that all time in the chat

**Comment by THEREALWWEFAN231** [comment]
Xray advertisement? Whats that?

**Comment by Zasty** [comment]
![imagen](https://user-images.githubusercontent.com/20426942/82170738-9ee4de80-98c5-11ea-8eaa-7f9020d39a8e.png)
That.

**Comment by THEREALWWEFAN231** [comment]
This is already added in/for the next update(3.1) by adding -Ddisablefabricindigomessage=true
