### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Louis-mrn** [THEREALWWEFAN231/wwe#522]
**WWE version:** last version
**Minecraft version:** 1.15.2
**Operating system:** Windows 10
**Optifine/Other mods:** Optifine

**Whats the issue:** Block ESP doesn't work

**Crash-report(Would be very useful also please format):** No crash

**Comment by THEREALWWEFAN231** [comment]
This has already been fixed in the next update, ull have to wait till then.
