### ISSUE TITLE
AntiAnimation Module

### ISSUE THREAD

**Issue by ToasterBathMaster** [THEREALWWEFAN231/wwe#526]
**Minecraft Version**
Any version, doesn't matter.

**What is the suggestion**
To make an AntiAnimation module that disables animations like the annoying fire animation that takes up a good 40 percent of the screen or the nausea animation.

**Why it will be useful**
The fire animation and other animations make it difficult for someone to see in difficult situations (fire: fighting blazes, when you're stuck in lava, etc.) This will make gameplay a lot less cluttered and allow the player to stay focused on their attacker. 
I have had multiple times where I run for water in the middle of a fight because I can't see for my life because of the dumb fire animation.

**Comment by THEREALWWEFAN231** [comment]
> No Render
