### ISSUE TITLE
Sky Flickers When Using Fullbright

### ISSUE THREAD

**Issue by BleachDrinker420** [THEREALWWEFAN231/wwe#55]
**WWE version:** 
_2.7.2_
**Minecraft version:** 
_1.14.3_
**Operating system:** 
_Windows 10_
**Optifine/Other mods:** 
_No Other Mods_
**Whats the issue:** 
When Using Fullbright in gamma mode the sky flickers, this is especially noticable when using xray (only happens at night)
**Crash-report(Would be very useful also please format):**

**Comment by Mac-au** [comment]
Just though I'd note that this also happens with fullbright in potion mode

**Comment by BleachDrinker420** [comment]
oh, yea, i'm dumb, i meant potion mode

**Comment by vungsung** [comment]
3.0 solved this problem.
