### ISSUE TITLE
DOWNLOAD LINK EXPIRED?

### ISSUE THREAD

**Issue by BlackmanWhite** [THEREALWWEFAN231/wwe#60]
When I try to download the WWE client from "https://wweclient.com/AdDownload.php?MinecraftVersion=1.14.3%20fabric&RandomString=XMb218jTkw" (the original site)

It just returns "An error occurred, download probably expired"

**Comment by THEREALWWEFAN231** [comment]
Re go to https://wweclient.com/AdDownload.php?MinecraftVersion=1.14.3%20fabric , with no random string to generate a new "key", you must have waited like 2-3 minutes, so then it expired
