### ISSUE TITLE
NoBob

### ISSUE THREAD

**Issue by ILikeTrains27** [THEREALWWEFAN231/wwe#61]
**Minecraft Version**
All of them that have wwe client.
**What is the suggestion**
Add a NoBob module that stops the camera from bobbing as you walk.
**Why it will be useful**
Because if you disable View Bobbing in Video Settings it just stops your hand from bobbing but not the screen.

**Comment by WaffleTraits** [comment]
Just tested this, camera and hand do not bob when View Bobbing is disabled (WWE 2.7.2, 1.14.3)

**Comment by ILikeTrains27** [comment]
yeah I found out that for some reason this is fixed when you enable tracers, search, trajectories, or waypoints

**Comment by THEREALWWEFAN231** [comment]
Im not fully sure what you guys are talking about, but i assume the fact that tracers and acouple other modules stop the camera bob(only in 1.14) and this has been fixed for the next update
