### ISSUE TITLE
Autofish is nonfunctional

### ISSUE THREAD

**Issue by Mac-au** [THEREALWWEFAN231/wwe#62]
**WWE version: 2.7.2** 
**Minecraft version: 1.14.3** 
**Operating system: Windows 10** 
**Optifine/Other mods: OptiFine 1.14.3 HD U F1, Optifabric 0.3.2, Fabric API 0.30, and Earthcomputer's Clientcommands 2.20** 

**Whats the issue: autofish left clicks instead of right clicking when a fish could be caught, and doesn't recast**

**Comment by Paralusion** [comment]
Already a known bug for WWE versions that are higher than 1.12.2, should be fixed next update.

**Comment by Mac-au** [comment]
Got it
