### ISSUE TITLE
Suggestion make every module 1 word

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#63]
**Minecraft Version**
Every
**What is the suggestion**
Make every module one word, so remove the spaces.
**Why it will be useful**
It can get confusing and it's basically a gamble when trying to bind or toggle through commands.

**Comment by THEREALWWEFAN231** [comment]
Sorry, but no, I think this makes it unique to other clients, and honestly why do clients have no spaces(that's not a question to be answered...)
