### ISSUE TITLE
Suggestion visual range

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#65]
**Minecraft Version**
Every
**What is the suggestion**
Visualrange, says in chat, or at the top bar where "server hasn't loaded for .... seconds> (make this a choice where it goes) when a player comes into the renderdistance of you. Also add an option to show their coordinates behind it. Like this: Notch has entered visual range. (434 64 -43) 
**Why it will be useful**
It will make it very easy to track people and it's the fastest way of seeing who comes near you.

**Comment by THEREALWWEFAN231** [comment]
This seems a little useless... due to tracers nametags and radar...

**Comment by THEREALWWEFAN231** [comment]
I find this to be one of the most cliche stupidest things in 2b2t clients therefore i dont like it.. & it wont be added
