### ISSUE TITLE
[Suggestion] Change the defaults of x-ray

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#66]
**Minecraft Version**
All
**What is the suggestion**
Change the defaults for x-ray to contain the following items:
Coal_Ore
ron_Ore
Gold_Ore
Lapis_Ore
Diamond_Ore
Emerald_Ore
Lava
Flowing_Lava
Water
Flowing_Water
Mob_Spawner

Also add a message on toggling the x-ray which explains how to add and remove items from xray.
**Why it will be useful**
People won't have to constantly come in the Discord and ask how to add things to x-ray or how to make it work.

**Comment by THEREALWWEFAN231** [comment]
There was some defaults added in 3.0
