### ISSUE TITLE
[suggestion] Add 'Enchants' Option to Nametags

### ISSUE THREAD

**Issue by WaffleTraits** [THEREALWWEFAN231/wwe#68]
**Minecraft Version**
Any
**What is the suggestion**
Add option to Nametags that shows the enchants of a player's held item(s) and equipped armor
**Why it will be useful**
Will allow you to see enchants on players' armor and items.

**Comment by THEREALWWEFAN231** [comment]
Your already suppose to see enchants but due to a bug in the 1.14.3 version you cant, but a enchant option to turn it on or off will be good

**Comment by THEREALWWEFAN231** [comment]
As said above this was a bug(that was eventually fixed) and either way there was an option added for disabling in 3.0
