### ISSUE TITLE
Inventory Walk Bug

### ISSUE THREAD

**Issue by mememasterlord32345** [THEREALWWEFAN231/wwe#7]
**WWE version: 2.7.2** 
**Minecraft version: 1.14.2** 
**Operating system: Windows 10** 
**Optifine/Other mods: None** 

**Whats the issue: Inventory Walk lets you sprint in place** 
http://media.methamphetamine.solutions/4a0vc8n4.mp4 Clip of the issue

**Comment by THEREALWWEFAN231** [comment]
Thats interesting
