### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by codemaster101gangster** [THEREALWWEFAN231/wwe#71]
**Minecraft Version**
1.14.3
**What is the suggestion**
Make the aim assist more legit and add auto fish 
**Why it will be useful**
There is no really legit way to legit cheat. Aim assist is very obvious maybe some smoothing would be nice. Auto fish would be really nice because you can just afk and fish.

**Comment by THEREALWWEFAN231** [comment]
There is auto fish, but theres alot of people saying its not working, and i have seen it happen once so ill have to look at that

**Comment by THEREALWWEFAN231** [comment]
As said in another issue there was a smooth or legit(i dont remember) mode added in 3.0 while its not the best i  think its the best im going add to wwe client
