### ISSUE TITLE
Cannot launch minecraft in Arch linux

### ISSUE THREAD

**Issue by zahariestefan** [THEREALWWEFAN231/wwe#73]
Hello, my minecraft isn't launching if I add WWE client to fabric.

**System info**(in case it helps):
Minecraft Launcher: TLauncher
WWE Version: 2.7.2 for MC 1.14.3
OS: ArcoLinuxD 19.06.1
Kernel: 5.1.16-zen1-1-zen
CPU: i5-4200U
GPU: Intel HD 4400 (integrated)

**Java version**:
Return of `java -version`:
openjdk version "12.0.1" 2019-04-16
OpenJDK Runtime Environment (build 12.0.1+12)
OpenJDK 64-Bit Server VM (build 12.0.1+12, mixed mode)

_**The crash report**_:

> ---- Minecraft Crash Report ----
> // Quite honestly, I wouldn't worry myself about that.
> 
> Time: 7/9/19 6:24 PM
> Description: Initializing game
> 
> java.lang.ArrayIndexOutOfBoundsException: -63438791
> 	at sun.font.FileFontStrike.setCachedGlyphPtr(FileFontStrike.java:520)
> 	at sun.font.FileFontStrike.setCachedGlyphPtr(FileFontStrike.java:537)
> 	at sun.font.FileFontStrike.getSlot0GlyphImagePtrs(FileFontStrike.java:449)
> 	at sun.font.CompositeStrike.getGlyphImagePtrs(CompositeStrike.java:115)
> 	at sun.font.GlyphList.mapChars(GlyphList.java:272)
> 	at sun.font.GlyphList.setFromString(GlyphList.java:244)
> 	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:71)
> 	at sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
> 	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
> 	at wwe.jfbI.crKo(Unknown Source)
> 	at wwe.jfbI.ZvVY(Unknown Source)
> 	at wwe.jfbI.<init>(Unknown Source)
> 	at wwe.hJuW.IbrW(Unknown Source)
> 	at wwe.hJuW.<init>(Unknown Source)
> 	at wwe.ddBF.Zprf(Unknown Source)
> 	at wwe.dcvG.Nkub(Unknown Source)
> 	at net.minecraft.class_310.handler$init$zde001(class_310.java:6522)
> 	at net.minecraft.class_310.method_1503(class_310.java:613)
> 	at net.minecraft.class_310.method_1514(class_310.java:395)
> 	at net.minecraft.client.main.Main.main(Main.java:154)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 
> 
> A detailed walkthrough of the error, its code path and all known details is as follows:
> ---------------------------------------------------------------------------------------
> 
> -- Head --
> Thread: Client thread
> Stacktrace:
> 	at sun.font.FileFontStrike.setCachedGlyphPtr(FileFontStrike.java:520)
> 	at sun.font.FileFontStrike.setCachedGlyphPtr(FileFontStrike.java:537)
> 	at sun.font.FileFontStrike.getSlot0GlyphImagePtrs(FileFontStrike.java:449)
> 	at sun.font.CompositeStrike.getGlyphImagePtrs(CompositeStrike.java:115)
> 	at sun.font.GlyphList.mapChars(GlyphList.java:272)
> 	at sun.font.GlyphList.setFromString(GlyphList.java:244)
> 	at sun.java2d.pipe.GlyphListPipe.drawString(GlyphListPipe.java:71)
> 	at sun.java2d.pipe.ValidatePipe.drawString(ValidatePipe.java:165)
> 	at sun.java2d.SunGraphics2D.drawString(SunGraphics2D.java:2928)
> 	at wwe.jfbI.crKo(Unknown Source)
> 	at wwe.jfbI.ZvVY(Unknown Source)
> 	at wwe.jfbI.<init>(Unknown Source)
> 	at wwe.hJuW.IbrW(Unknown Source)
> 	at wwe.hJuW.<init>(Unknown Source)
> 	at wwe.ddBF.Zprf(Unknown Source)
> 	at wwe.dcvG.Nkub(Unknown Source)
> 	at net.minecraft.class_310.handler$init$zde001(class_310.java:6522)
> 	at net.minecraft.class_310.method_1503(class_310.java:613)
> 
> -- Initialization --
> Details:
> Stacktrace:
> 	at net.minecraft.class_310.method_1514(class_310.java:395)
> 	at net.minecraft.client.main.Main.main(Main.java:154)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:170)
> 	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:129)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:26)
> 
> -- System Details --
> Details:
> 	Minecraft Version: 1.14.3
> 	Operating System: Linux (amd64) version 5.1.16-zen1-1-zen
> 	Java Version: 1.8.0_51, Oracle Corporation
> 	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
> 	Memory: 158617304 bytes (151 MB) / 457527296 bytes (436 MB) up to 7282622464 bytes (6945 MB)
> 	JVM Flags: 4 total; -Xmn128M -Xmx6958M -Xss1M -XX:+UseConcMarkSweepGC
> 	Fabric Mods: 
> 		blue_endless_jankson: jankson 1.1.0
> 		cloth: Cloth Events 0.3.1+build.23
> 		cloth-config2: Cloth Config v2 0.2.0
> 		fabric: Fabric API 0.3.0+build.188
> 		fabric-api-base: fabric-api-base 0.1.0+59147463
> 		fabric-biomes-v1: fabric-biomes-v1 0.1.0+896c7fbb
> 		fabric-commands-v0: fabric-commands-v0 0.1.1+25fd0c52
> 		fabric-containers-v0: fabric-containers-v0 0.1.2+25fd0c52
> 		fabric-content-registries-v0: fabric-content-registries-v0 0.1.1+05f11b75
> 		fabric-crash-report-info-v1: fabric-crash-report-info-v1 0.1.0+59147463
> 		fabric-events-interaction-v0: fabric-events-interaction-v0 0.1.0+59147463
> 		fabric-events-lifecycle-v0: fabric-events-lifecycle-v0 0.1.0+59147463
> 		fabric-item-groups-v0: fabric-item-groups-v0 0.1.0+f0d56800
> 		fabric-keybindings-v0: fabric-keybindings-v0 0.1.1+7dfef87c
> 		fabric-loot-tables-v1: fabric-loot-tables-v1 0.1.0+43028fa6
> 		fabric-mining-levels-v0: fabric-mining-levels-v0 0.1.0+bdffbb2c
> 		fabric-models-v0: fabric-models-v0 0.1.0+59147463
> 		fabric-networking-blockentity-v0: fabric-networking-blockentity-v0 0.1.1+25fd0c52
> 		fabric-networking-v0: fabric-networking-v0 0.1.2+200eb5c2
> 		fabric-object-builders-v0: fabric-object-builders-v0 0.1.1+39ff57de
> 		fabric-registry-sync-v0: fabric-registry-sync-v0 0.2.2+f0d56800
> 		fabric-renderer-api-v1: fabric-renderer-api-v1 0.1.0+02a46d5b
> 		fabric-renderer-indigo: fabric-renderer-indigo 0.1.7+029ec62e
> 		fabric-rendering-data-attachment-v1: fabric-rendering-data-attachment-v1 0.1.0+02a46d5b
> 		fabric-rendering-fluids-v1: fabric-rendering-fluids-v1 0.1.0+dc4c57c2
> 		fabric-rendering-v0: fabric-rendering-v0 0.1.1+6dad974e
> 		fabric-resource-loader-v0: fabric-resource-loader-v0 0.1.1+59147463
> 		fabric-tag-extensions-v0: fabric-tag-extensions-v0 0.1.1+c189dc5c
> 		fabric-textures-v0: fabric-textures-v0 0.1.4+792c1c35
> 		fabricloader: Fabric Loader 0.4.8+build.155
> 		mm: Manningham Mills 1.6
> 		modmenu: Mod Menu 1.6.2-92
> 		net_fabricmc_stitch: stitch 0.2.1.61
> 		optifabric: Optifabric 0.3.2
> 		org_slf4j_slf4j-api: slf4j-api 1.7.26
> 		org_slf4j_slf4j-simple: slf4j-simple 1.7.26
> 		org_zeroturnaround_zt-zip: zt-zip 1.13
> 		roughlyenoughitems: Roughly Enough Items 2.9.6+build.138
> 		voxelmap: VoxelMap 1.9.11
> 		waila: Hwyla 1.9.16
> 		wwefan: WWE 1.14.3
> 	Launched Version: fabric-loader-0.4.8+build.155-1.14.3
> 	LWJGL: 3.2.2 build 10
> 	OpenGL: Mesa DRI Intel(R) Haswell Mobile  GL version 3.0 Mesa 19.1.1, Intel Open Source Technology Center
> 	GL Caps: Using GL 1.3 multitexturing.
> Using GL 1.3 texture combiners.
> Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
> Shaders are available because OpenGL 2.1 is supported.
> VBOs are available because OpenGL 1.5 is supported.
> 
> 	Using VBOs: Yes
> 	Is Modded: Definitely; Client brand changed to 'fabric'
> 	Type: Client (map_client.txt)
> 	Resource Packs: vanilla, file/Stevens-Traditional-64x64-1.14.3.zip
> 	Current Language: English (US)
> 	CPU: 4x Intel(R) Core(TM) i5-4200U CPU @ 1.60GHz
> #@!@# Game crashed! Crash report saved to: #@!@# /home/justme/.minecraft/crash-reports/crash-2019-07-09_18.24.03-client.txt
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (47 ms)
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 255
[Launcher] [Crash] Found crash report file: /home/justme/.minecraft/crash-reports/crash-2019-07-09_18.24.03-client.txt
[Crash] Found crash report file: /home/justme/.minecraft/crash-reports/crash-2019-07-09_18.24.03-client.txt

P.S.: In Fedora 30 it was working just fine

**Comment by THEREALWWEFAN231** [comment]
Interesting

**Comment by zahariestefan** [comment]
Solved by installing some java packages (I think missing openjfx was the problem) and forcing TLauncher to use /usr/bin/java
