### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by codemaster101gangster** [THEREALWWEFAN231/wwe#74]
**Minecraft Version**
1.14.3
**What is the suggestion**
Add vanish to 1.14+
**Why it will be useful**
So you can do the 1 person dupe using wwe client.

**Comment by THEREALWWEFAN231** [comment]
It's in the 1.14 version, not working the same as the 1.13 and below version, and it doesnt work on many servers?, you can reply if you would like.

**Comment by codemaster101gangster** [comment]
So you can use the dupe in 1.14 but it doesn't work on most server?
