### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by imjohne** [THEREALWWEFAN231/wwe#76]
**WWE version: 2.7.2
**Minecraft version: 1.12.2
**Operating system:** Windows 7
**Optifine/Other mods: Forge with Optifine

**Whats the issue:** 
Im trying to use the .vanish dismount/remount dupe glitch but now whenever I do .vanish dismount nothing happens and .vanish remount crashes the game

Also chunks arent loading and whenever destroy blocks to far away from where I joined the blocks arent breaking
**Crash-report(Would be very useful also please format):**
"The game crashed whilst updating screen events
Error: java.lang.NullPointerException: Updating screen events"

Temporary ish fix I tried to join with another client and i did something but now im stuck again...

https://youtu.be/27ZgDYsSIb0

**Comment by imjohne** [comment]
My bad it's a bug that happens whenever you accidently types .vanish remount strangely and the crash happens because you type it again...

**Comment by THEREALWWEFAN231** [comment]
I dont know exactly why you get stuck like that where you cant break blocks, what i did on a different server   close minecraft, reconnect(to the server, you can use wwe or something else doesnt matter)(so you are the exact location you are stuck), then place a boat, its hard to place boats without water, but you can do it by hovering over the farthest distance you can reach and spam placing the boat, and move slightly out of place range till you place a boat(might take a hot minute), then get into the boat, and you shouldent be glitched.
