### ISSUE TITLE
Bug: Better selection mode: facing draws weird boxes around non full blocks

### ISSUE THREAD

**Issue by Godeps2891** [THEREALWWEFAN231/wwe#790]
**Inertia Utility Mod version:** 3.1.3
**Minecraft version:** All (Probably, tested 1.12 and 1.16)
**Operating system:** Win10
**Optifine/Other mods:** None

**What's the issue:** Better Selection with mode set to facing draws weird and inaccurate boxes around (mostly the underside) of non full blocks

Video showing the issue, obviously these aren't all the blocks affected 
https://www.youtube.com/watch?v=bEDxH8VAAVs

**Comment by THEREALWWEFAN231** [comment]
Fixed in the next update.
