### ISSUE TITLE
Suggestion cool animations

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#81]
**Minecraft Version**
all
**What is the suggestion**
Add several animations to things such as the feature list (the same thing future does, it goes in slowly and out slowly when toggling. Also the same thing Future does with the chat. It pops in slowly and moves coordinates above the chat too.
**Why it will be useful**
Makes it look fancy :)

**Comment by THEREALWWEFAN231** [comment]
This was added in 3.0
