### ISSUE TITLE
Bug - Kill aura attacks armour stands

### ISSUE THREAD

**Issue by Orange65** [THEREALWWEFAN231/wwe#82]
**WWE version:** 
2.7.2, might affect other versions

**Minecraft version:** 
1.12.2, might affect other versions
**Operating system:** 
Windows 10 

**Optifine/Other mods:** 
None

**Whats the issue:** 
Killaura attacks armour stands. Either this is a bug or there should be an option to disable this.

**Crash-report(Would be very useful also please format):**
n/a

**Comment by THEREALWWEFAN231** [comment]
I believe this was fixed in 3.0
