### ISSUE TITLE
Suggestion change values through chat

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#87]
**Minecraft Version**
all
**What is the suggestion**
Change values through chat like some other clients (Future) do. For example: .value entity_speed 100, or .value kill_aura cps 0.3
**Why it will be useful**
Allows you to precisely change the value of a module. It should also allow you to go over the traditional limit. Very experimental.

**Comment by THEREALWWEFAN231** [comment]
Already a thing.. lmao
