### ISSUE TITLE
Low shield

### ISSUE THREAD

**Issue by THEREALWWEFAN231** [THEREALWWEFAN231/wwe#89]
**WWE version:** 
**Minecraft version:** 
**Operating system:** 
**Optifine/Other mods:** 

**Whats the issue:** 
Low shield not working

**Crash-report(Would be very useful also please format):**

**Comment by THEREALWWEFAN231** [comment]
Couldn't replicate...

**Comment by SylveonBottle** [comment]
I've got the bug. 1.14.3 optifine and optifabric. It may be related to something with the GUI or other render settings.

**Comment by THEREALWWEFAN231** [comment]
Fixed
