### ISSUE TITLE
Suggestion GUI themes

### ISSUE THREAD

**Issue by Paralusion** [THEREALWWEFAN231/wwe#91]
**Minecraft Version**
All
**What is the suggestion**
Make some cool GUI themes, maybe an oldschool one, a more mondern one, etc.. Everyone likes to have a custom style.
**Why it will be useful**
Lookin fancy.

**Comment by THEREALWWEFAN231** [comment]
This will be put on hold for a bit.. for a while..., I have coded to many gui's in the last 6 months and dont feel like it rn.

**Comment by Paralusion** [comment]
very understandable, thanks
