### ISSUE TITLE
Bug - doing ".vanish remount" crashes the game when already on an entity

### ISSUE THREAD

**Issue by Orange65** [THEREALWWEFAN231/wwe#93]
**WWE version:** 
2.7.2

**Minecraft version:** 
1.12.2

**Operating system:** 
Windows 10

**Optifine/Other mods:** 
none

**Whats the issue:** 
Doing ".vanish remount" crashes the game when already on an entity. Get on an entity, and instead of doing dismount, type ".vanish remount" and the game will crash. 

**Crash-report(Would be very useful also please format):**
https://pastebin.com/hL6ZG92r

**Comment by THEREALWWEFAN231** [comment]
you dident dismount yet, but i know about this, ill fix it soon

**Comment by Orange65** [comment]
> you dident dismount yet, but i know about this, ill fix it soon

I know, it's a crash report. It shouldnt crash the game

**Comment by THEREALWWEFAN231** [comment]
> > you dident dismount yet, but i know about this, ill fix it soon
> 
> I know, it's a crash report. It shouldnt crash the game

I know, hence ill fix it soon, fixed for the next update

**Comment by Orange65** [comment]
Alright thanks. I should also add I had a crashe when toggling freecam on an entity, I will try and pinpoint this tomorrow.
