### ISSUE TITLE
World Downloader

### ISSUE THREAD

**Issue by BleachDrinker420** [THEREALWWEFAN231/wwe#94]
**Minecraft Version**
All
**What is the suggestion**
Add a built in world downloader to the client, like the one in future and a few other clients.
**Why it will be useful**
Its useful to download your dupe stash.

**Comment by THEREALWWEFAN231** [comment]
I have tried this many times before and just couldent get it to work, idk how to make it work/get the source

**Comment by SylveonBottle** [comment]
This may be helpful. @THEREALWWEFAN231 

https://github.com/Pokechu22/WorldDownloader/tree/v4/1.14.3

**Comment by THEREALWWEFAN231** [comment]
> This may be helpful. @THEREALWWEFAN231
> 
> https://github.com/Pokechu22/WorldDownloader/tree/v4/1.14.3

This is what I don't understand the source isn't there, they have the patches which are useful, but the source isn't there, therefore I don't know how I would add it.

**Comment by THEREALWWEFAN231** [comment]
oops didn't mean to close this

**Comment by THEREALWWEFAN231** [comment]
Maybe if i can actually find the source code to world downloader, but even then idk
