### ISSUE TITLE
Suggestion: Implement Optifabric within the WWE Mod

### ISSUE THREAD

**Issue by VPG-FNBRGhosty** [THEREALWWEFAN231/wwe#95]
Upon using Optifabric with the latest version of Optifine, you will usually get this: OpenGL Error:1286 (Invalid framebuffer error) spamming your console, would be nice to have it implemented with WWE

**Comment by SylveonBottle** [comment]
Pretty sure that OpenGL error has nothing to do with OptiFabric. Putting OptiFabric into WWE isn't going to get rid of it.

**Comment by Paralusion** [comment]
i use OptiFabric with WWE, and it works fine, never had an issue with it. but, i've also never had a issue with WWE standalone.

**Comment by THEREALWWEFAN231** [comment]
> Upon using Optifabric with the latest version of Optifine, you will usually get this: OpenGL Error:1286 (Invalid framebuffer error) spamming your console, would be nice to have it implemented with WWE

Its probably waypoints, causing the open gl error, and optifabric will not be included in the wwe jar, sorry
